import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  async redirects() {
    return [
      {
        source: "/journal/recolta-2024-in-moldova-ce-inseamna-pentru-tine",
        destination:
          "/journal/recolta-2026-in-moldova-ce-inseamna-pentru-tine",
        permanent: true,
      },
    ];
  },
  images: {
    formats: ["image/avif", "image/webp"],
    minimumCacheTTL: 60 * 60 * 24 * 30,
    remotePatterns: [
      { protocol: "https", hostname: "images.unsplash.com" },
      { protocol: "https", hostname: "picsum.photos" },
      { protocol: "https", hostname: "**.vinintel.ro" },
      { protocol: "https", hostname: "**.public.blob.vercel-storage.com" },
      // Romanian winery sites (replace with real URLs as crame submit photos)
      { protocol: "https", hostname: "www.davino.ro" },
      { protocol: "https", hostname: "davino.ro" },
      { protocol: "https", hostname: "www.cramele-recas.ro" },
      { protocol: "https", hostname: "cramele-recas.ro" },
      { protocol: "https", hostname: "www.cramelerecas.ro" },
      { protocol: "https", hostname: "cramelerecas.ro" },
      { protocol: "https", hostname: "www.cotnari.ro" },
      { protocol: "https", hostname: "www.avincis.ro" },
      { protocol: "https", hostname: "www.liliac.ro" },
      { protocol: "https", hostname: "www.budureasca.ro" },
      { protocol: "https", hostname: "www.lacertawinery.ro" },
      { protocol: "https", hostname: "www.jidvei.ro" },
      { protocol: "https", hostname: "**.emag.ro" },
      { protocol: "https", hostname: "emag.ro" },
      { protocol: "https", hostname: "serve.ro" },
      { protocol: "https", hostname: "www.serve.ro" },
      { protocol: "https", hostname: "cramaoprisor.ro" },
      { protocol: "https", hostname: "www.cramaoprisor.ro" },
      { protocol: "https", hostname: "liliac.com" },
      { protocol: "https", hostname: "www.liliac.com" },
      { protocol: "https", hostname: "casadevinuricotnari.ro" },
      { protocol: "https", hostname: "www.casadevinuricotnari.ro" },
      { protocol: "https", hostname: "domeniulcoroanei.ro" },
      { protocol: "https", hostname: "www.domeniulcoroanei.ro" },
      { protocol: "https", hostname: "tohani.ro" },
      { protocol: "https", hostname: "www.tohani.ro" },
      { protocol: "https", hostname: "petrovaselo.com" },
      { protocol: "https", hostname: "www.petrovaselo.com" },
      { protocol: "https", hostname: "cramagirboiu.ro" },
      { protocol: "https", hostname: "www.cramagirboiu.ro" },
      { protocol: "https", hostname: "cramabasilescu.ro" },
      { protocol: "https", hostname: "www.cramabasilescu.ro" },
      { protocol: "https", hostname: "domeniilesamburesti.ro" },
      { protocol: "https", hostname: "www.domeniilesamburesti.ro" },
      { protocol: "https", hostname: "ballageza.ro" },
      { protocol: "https", hostname: "www.ballageza.ro" },
      { protocol: "https", hostname: "corcova.ro" },
      { protocol: "https", hostname: "www.corcova.ro" },
      { protocol: "https", hostname: "stirbey.com" },
      { protocol: "https", hostname: "www.stirbey.com" },
      { protocol: "https", hostname: "vinarte.ro" },
      { protocol: "https", hostname: "www.vinarte.ro" },
      { protocol: "https", hostname: "halewood.com.ro" },
      { protocol: "https", hostname: "www.halewood.com.ro" },
      { protocol: "https", hostname: "villavinea.com" },
      { protocol: "https", hostname: "www.villavinea.com" },
    ],
  },
  poweredByHeader: false,
  compress: true,
};

export default nextConfig;
