/**
 * Additional Romanian dishes learned from the first human curation batch.
 * Broad FoodCategoryId stays for scoring. These are candidate knowledge.
 */
import type { RomanianDishProfile } from "@/lib/pairing/romanian-dishes";

function dish(profile: RomanianDishProfile): RomanianDishProfile {
  return profile;
}

export const ROMANIAN_DISH_EXTENSIONS: RomanianDishProfile[] = [
  dish({
    id: "sarmale-in-foi-de-vita",
    name: "Sarmale în foi de viță",
    foodCategory: "sarmale",
    protein: "pork",
    cookingMethods: ["stewed"],
    intensity: 3,
    fat: 3,
    salt: 3,
    acidity: 3,
    sweetness: 2,
    smoke: 1,
    spice: 2,
    sour: true,
    aliases: ["sarmale in foi de vita", "sarmale foi vita"],
    family: "vine-leaf-roll",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 5,
    specificity: 4,
  }),
  dish({
    id: "ardei-umpluti-de-post",
    name: "Ardei umpluți de post",
    foodCategory: "vegetable",
    protein: "none",
    cookingMethods: ["baked", "stewed"],
    intensity: 3,
    fat: 2,
    salt: 3,
    acidity: 3,
    sweetness: 2,
    smoke: 1,
    spice: 2,
    tomatoRich: true,
    aliases: ["ardei umpluti de post"],
    family: "stuffed-veg-fasting",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 4,
  }),
  dish({
    id: "dovlecei-umpluti-de-post",
    name: "Dovlecei umpluți de post",
    foodCategory: "vegetable",
    protein: "none",
    cookingMethods: ["baked", "stewed"],
    intensity: 3,
    fat: 2,
    salt: 2,
    acidity: 2,
    sweetness: 2,
    smoke: 1,
    spice: 2,
    tomatoRich: true,
    aliases: ["dovlecei umpluti de post"],
    family: "stuffed-veg-fasting",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 4,
  }),
  dish({
    id: "mancare-de-praz-cu-masline",
    name: "Mâncare de praz cu măsline",
    foodCategory: "vegetable",
    protein: "none",
    cookingMethods: ["stewed"],
    intensity: 3,
    fat: 2,
    salt: 3,
    acidity: 3,
    sweetness: 1,
    smoke: 1,
    spice: 2,
    aliases: ["praz cu masline", "mancare de praz"],
    family: "vegetable-stew",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 4,
  }),
  dish({
    id: "ciulama-de-ciuperci",
    name: "Ciulama de ciuperci",
    foodCategory: "vegetable",
    protein: "none",
    cookingMethods: ["stewed"],
    intensity: 3,
    fat: 4,
    salt: 2,
    acidity: 1,
    sweetness: 1,
    smoke: 1,
    spice: 1,
    creamRich: true,
    aliases: ["ciulama ciuperci"],
    family: "mushroom-cream",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 4,
  }),
  dish({
    id: "tocanita-de-ciuperci",
    name: "Tocăniță de ciuperci",
    foodCategory: "vegetable",
    protein: "none",
    cookingMethods: ["stewed"],
    intensity: 3,
    fat: 3,
    salt: 3,
    acidity: 2,
    sweetness: 1,
    smoke: 1,
    spice: 2,
    tomatoRich: true,
    aliases: ["tocanita de ciuperci"],
    family: "mushroom",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 4,
  }),
  dish({
    id: "placinte-sarate-vegetariene",
    name: "Plăcinte sărate vegetariene",
    foodCategory: "vegetable",
    protein: "none",
    cookingMethods: ["baked"],
    intensity: 3,
    fat: 3,
    salt: 3,
    acidity: 2,
    sweetness: 1,
    smoke: 1,
    spice: 1,
    aliases: ["placinte sarate"],
    family: "savory-pie",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 3,
  }),
  dish({
    id: "plachie-de-salau",
    name: "Plachie de șalău",
    foodCategory: "fish",
    protein: "fish",
    cookingMethods: ["baked", "stewed"],
    intensity: 3,
    fat: 2,
    salt: 3,
    acidity: 3,
    sweetness: 1,
    smoke: 1,
    spice: 2,
    tomatoRich: true,
    aliases: ["plachie de salau"],
    family: "pikeperch",
    romanian: true,
    romanianRegion: "Dobrogea",
    discoveryValue: 5,
    specificity: 4,
  }),
  dish({
    id: "saramura-de-pastrav",
    name: "Saramură de păstrăv",
    foodCategory: "fish",
    protein: "fish",
    cookingMethods: ["grilled", "boiled"],
    intensity: 3,
    fat: 2,
    salt: 5,
    acidity: 4,
    sweetness: 1,
    smoke: 1,
    spice: 2,
    sour: true,
    aliases: ["saramura de pastrav"],
    family: "trout",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 4,
    specificity: 4,
  }),
  dish({
    id: "pastrav-prajit",
    name: "Păstrăv prăjit",
    foodCategory: "fish",
    protein: "fish",
    cookingMethods: ["fried"],
    intensity: 3,
    fat: 3,
    salt: 2,
    acidity: 2,
    sweetness: 1,
    smoke: 1,
    spice: 1,
    fried: true,
    aliases: ["pastrav prajit"],
    family: "trout",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 3,
  }),
  dish({
    id: "salau-la-cuptor",
    name: "Șalău la cuptor",
    foodCategory: "fish",
    protein: "fish",
    cookingMethods: ["baked"],
    intensity: 2,
    fat: 2,
    salt: 2,
    acidity: 2,
    sweetness: 1,
    smoke: 1,
    spice: 1,
    aliases: ["salau la cuptor"],
    family: "pikeperch",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 4,
    specificity: 4,
  }),
  dish({
    id: "scrumbie-de-dunare-la-gratar",
    name: "Scrumbie de Dunăre la grătar",
    foodCategory: "grilled_fish",
    protein: "fish",
    cookingMethods: ["grilled"],
    intensity: 3,
    fat: 4,
    salt: 3,
    acidity: 2,
    sweetness: 1,
    smoke: 2,
    spice: 1,
    aliases: ["scrumbie la gratar"],
    family: "delta-fish",
    romanian: true,
    romanianRegion: "Delta Dunarii",
    discoveryValue: 5,
    specificity: 4,
  }),
  dish({
    id: "bors-de-peste",
    name: "Borș de pește",
    foodCategory: "fish",
    protein: "fish",
    cookingMethods: ["boiled"],
    intensity: 3,
    fat: 2,
    salt: 3,
    acidity: 5,
    sweetness: 1,
    smoke: 1,
    spice: 2,
    sour: true,
    aliases: ["bors de peste"],
    family: "sour-soup",
    romanian: true,
    romanianRegion: "Delta Dunarii",
    discoveryValue: 5,
  }),
  dish({
    id: "salata-de-icre-de-crap",
    name: "Salată de icre de crap",
    foodCategory: "fish",
    protein: "seafood",
    cookingMethods: ["raw"],
    intensity: 3,
    fat: 4,
    salt: 4,
    acidity: 3,
    sweetness: 1,
    smoke: 1,
    spice: 1,
    aliases: ["icre de crap"],
    family: "roe-carp",
    romanian: true,
    romanianRegion: "Dobrogea",
    discoveryValue: 5,
    specificity: 4,
  }),
  dish({
    id: "salata-de-icre-de-stiuca",
    name: "Salată de icre de știucă",
    foodCategory: "fish",
    protein: "seafood",
    cookingMethods: ["raw"],
    intensity: 2,
    fat: 3,
    salt: 4,
    acidity: 3,
    sweetness: 1,
    smoke: 1,
    spice: 1,
    aliases: ["icre de stiuca", "salata de icre de stiuca"],
    family: "roe-pike",
    romanian: true,
    romanianRegion: "Dobrogea",
    discoveryValue: 5,
    specificity: 5,
  }),
  dish({
    id: "telemea-de-capra",
    name: "Telemea de capră",
    foodCategory: "cheese",
    protein: "none",
    cookingMethods: ["fermented"],
    intensity: 2,
    fat: 3,
    salt: 4,
    acidity: 4,
    sweetness: 1,
    smoke: 1,
    spice: 1,
    aliases: ["telemea capra", "branza de capra", "branza capra"],
    family: "fresh-cheese",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 4,
    specificity: 4,
  }),
  dish({
    id: "telemea-de-oaie",
    name: "Telemea de oaie",
    foodCategory: "cheese",
    protein: "none",
    cookingMethods: ["fermented"],
    intensity: 3,
    fat: 3,
    salt: 5,
    acidity: 3,
    sweetness: 1,
    smoke: 1,
    spice: 1,
    aliases: ["telemea oaie"],
    family: "fresh-cheese",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 3,
    specificity: 4,
  }),
  dish({
    id: "telemea-de-vaca",
    name: "Telemea de vacă",
    foodCategory: "cheese",
    protein: "none",
    cookingMethods: ["fermented"],
    intensity: 2,
    fat: 3,
    salt: 3,
    acidity: 3,
    sweetness: 1,
    smoke: 1,
    spice: 1,
    aliases: ["telemea vaca"],
    family: "fresh-cheese",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 2,
    specificity: 3,
  }),
  dish({
    id: "chiftele-prajite",
    name: "Chiftele prăjite",
    foodCategory: "pork",
    protein: "pork",
    cookingMethods: ["fried"],
    intensity: 3,
    fat: 4,
    salt: 3,
    acidity: 1,
    sweetness: 1,
    smoke: 1,
    spice: 2,
    fried: true,
    aliases: ["chiftele"],
    family: "fried-meatball",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 3,
  }),
  dish({
    id: "chiftele-marinate-in-sos-de-rosii",
    name: "Chiftele marinate în sos de roșii",
    foodCategory: "pork",
    protein: "pork",
    cookingMethods: ["stewed", "fried"],
    intensity: 4,
    fat: 4,
    salt: 3,
    acidity: 4,
    sweetness: 2,
    smoke: 1,
    spice: 2,
    tomatoRich: true,
    sour: true,
    aliases: ["chiftele marinate", "chiftele in sos"],
    family: "tomato-meatball",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 4,
  }),
  dish({
    id: "parjoale-moldovenesti",
    name: "Pârjoale moldovenești",
    foodCategory: "pork",
    protein: "pork",
    cookingMethods: ["fried"],
    intensity: 4,
    fat: 4,
    salt: 3,
    acidity: 1,
    sweetness: 1,
    smoke: 1,
    spice: 3,
    fried: true,
    aliases: ["parjoale", "parjoale moldovenesti"],
    family: "fried-meatball",
    romanian: true,
    romanianRegion: "Moldova",
    discoveryValue: 5,
  }),
  dish({
    id: "chiftele-de-ciuperci",
    name: "Chiftele de ciuperci",
    foodCategory: "vegetable",
    protein: "none",
    cookingMethods: ["fried"],
    intensity: 3,
    fat: 3,
    salt: 3,
    acidity: 2,
    sweetness: 1,
    smoke: 1,
    spice: 2,
    fried: true,
    aliases: ["chiftele de legume"],
    family: "veg-meatball",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 4,
  }),
  dish({
    id: "ciorba-radauteana",
    name: "Ciorbă rădăuțeană",
    foodCategory: "poultry",
    protein: "chicken",
    cookingMethods: ["boiled"],
    intensity: 3,
    fat: 3,
    salt: 3,
    acidity: 4,
    sweetness: 1,
    smoke: 1,
    spice: 2,
    sour: true,
    creamRich: true,
    aliases: ["ciorba radauteana"],
    family: "sour-soup",
    romanian: true,
    romanianRegion: "Moldova",
    discoveryValue: 5,
  }),
  dish({
    id: "ciorba-de-perisoare",
    name: "Ciorbă de perișoare",
    foodCategory: "pork",
    protein: "pork",
    cookingMethods: ["boiled"],
    intensity: 3,
    fat: 3,
    salt: 3,
    acidity: 4,
    sweetness: 1,
    smoke: 1,
    spice: 2,
    sour: true,
    aliases: ["ciorba de perisoare"],
    family: "sour-soup",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 3,
  }),
  dish({
    id: "ciorba-de-burta",
    name: "Ciorbă de burtă",
    foodCategory: "beef",
    protein: "beef",
    cookingMethods: ["boiled"],
    intensity: 3,
    fat: 4,
    salt: 3,
    acidity: 4,
    sweetness: 1,
    smoke: 1,
    spice: 2,
    sour: true,
    creamRich: true,
    aliases: ["ciorba de burta"],
    family: "sour-soup",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 4,
  }),
  dish({
    id: "ciorba-de-miel",
    name: "Ciorbă de miel",
    foodCategory: "festive_traditional",
    protein: "lamb",
    cookingMethods: ["boiled"],
    intensity: 3,
    fat: 3,
    salt: 3,
    acidity: 4,
    sweetness: 1,
    smoke: 1,
    spice: 2,
    sour: true,
    aliases: ["ciorba de miel"],
    family: "sour-soup",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 4,
  }),
  dish({
    id: "ciorba-de-fasole-cu-afumatura",
    name: "Ciorbă de fasole cu afumătură",
    foodCategory: "pork",
    protein: "pork",
    cookingMethods: ["boiled", "smoked"],
    intensity: 4,
    fat: 3,
    salt: 4,
    acidity: 3,
    sweetness: 1,
    smoke: 4,
    spice: 2,
    sour: true,
    aliases: ["ciorba de fasole"],
    family: "smoked-soup",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 4,
  }),
  dish({
    id: "ciorba-de-legume",
    name: "Ciorbă de legume",
    foodCategory: "vegetable",
    protein: "none",
    cookingMethods: ["boiled"],
    intensity: 2,
    fat: 1,
    salt: 2,
    acidity: 4,
    sweetness: 1,
    smoke: 1,
    spice: 1,
    sour: true,
    aliases: ["ciorba de legume"],
    family: "sour-soup",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 3,
  }),
  dish({
    id: "piftie-de-curcan",
    name: "Piftie de curcan",
    foodCategory: "poultry",
    protein: "turkey",
    cookingMethods: ["boiled"],
    intensity: 2,
    fat: 2,
    salt: 3,
    acidity: 2,
    sweetness: 1,
    smoke: 1,
    spice: 2,
    aliases: ["piftie de curcan"],
    family: "aspic-turkey",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 4,
  }),
  dish({
    id: "piftie-de-porc",
    name: "Piftie de porc",
    foodCategory: "pork",
    protein: "pork",
    cookingMethods: ["boiled"],
    intensity: 3,
    fat: 4,
    salt: 4,
    acidity: 2,
    sweetness: 1,
    smoke: 1,
    spice: 2,
    aliases: ["piftie de porc"],
    family: "aspic-pork",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 3,
  }),
  dish({
    id: "piept-de-rata",
    name: "Piept de rață",
    foodCategory: "poultry",
    protein: "duck",
    cookingMethods: ["roasted"],
    intensity: 4,
    fat: 4,
    salt: 3,
    acidity: 1,
    sweetness: 1,
    smoke: 2,
    spice: 1,
    aliases: ["piept de rata"],
    family: "duck-breast",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 3,
    specificity: 4,
  }),
  dish({
    id: "tocana-de-porc-cu-prune",
    name: "Tocană de porc cu prune",
    foodCategory: "pork",
    protein: "pork",
    cookingMethods: ["stewed"],
    intensity: 4,
    fat: 4,
    salt: 3,
    acidity: 2,
    sweetness: 3,
    smoke: 1,
    spice: 2,
    aliases: ["tocana de porc cu prune"],
    family: "pork-prune-stew",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 5,
    specificity: 5,
  }),
  dish({
    id: "peste-alb",
    name: "Pește alb",
    foodCategory: "fish",
    protein: "fish",
    cookingMethods: ["baked", "grilled"],
    intensity: 2,
    fat: 2,
    salt: 2,
    acidity: 2,
    sweetness: 1,
    smoke: 1,
    spice: 1,
    aliases: ["peste alb"],
    family: "white-fish",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 1,
    specificity: 1,
  }),
  dish({
    id: "cotlete-de-miel",
    name: "Cotlete de miel",
    foodCategory: "festive_traditional",
    protein: "lamb",
    cookingMethods: ["grilled", "roasted"],
    intensity: 4,
    fat: 3,
    salt: 3,
    acidity: 1,
    sweetness: 1,
    smoke: 2,
    spice: 2,
    aliases: ["cotlet de miel"],
    family: "roast-lamb",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 3,
    specificity: 3,
  }),
];
