/**
 * Curated Romanian dish library for editorial pairing drafts.
 * Not bottle evidence. Broad FoodCategoryId stays for scoring.
 */
import type { FoodCategoryId } from "@/lib/food-taxonomy";

export type DishProtein =
  | "pork"
  | "beef"
  | "lamb"
  | "chicken"
  | "duck"
  | "turkey"
  | "rabbit"
  | "game"
  | "fish"
  | "seafood"
  | "none";

export type CookingMethod =
  | "grilled"
  | "roasted"
  | "fried"
  | "stewed"
  | "smoked"
  | "boiled"
  | "baked"
  | "raw"
  | "fermented";

export type TraitLevel = 1 | 2 | 3 | 4 | 5;

export interface RomanianDishProfile {
  id: string;
  name: string;
  foodCategory: FoodCategoryId;
  protein: DishProtein;
  cookingMethods: CookingMethod[];
  intensity: TraitLevel;
  fat: TraitLevel;
  salt: TraitLevel;
  acidity: TraitLevel;
  sweetness: TraitLevel;
  smoke: TraitLevel;
  spice: TraitLevel;
  tomatoRich?: boolean;
  creamRich?: boolean;
  sour?: boolean;
  fried?: boolean;
  aliases: string[];
  family: string;
  romanian: boolean;
  romanianRegion: string | null;
  discoveryValue: TraitLevel;
}

function dish(
  profile: RomanianDishProfile,
): RomanianDishProfile {
  return profile;
}

export const ROMANIAN_DISHES: RomanianDishProfile[] = [
  dish({
    id: "sarmale",
    name: "Sarmale",
    foodCategory: "sarmale",
    protein: "pork",
    cookingMethods: ["stewed"],
    intensity: 4,
    fat: 4,
    salt: 3,
    acidity: 3,
    sweetness: 2,
    smoke: 1,
    spice: 2,
    sour: true,
    aliases: ["sarma", "sarmalute"],
    family: "cabbage-roll",
    romanian: true,
    romanianRegion: "Transilvania",
    discoveryValue: 4,
  }),
  dish({
    id: "varza-a-la-cluj",
    name: "Varza a la Cluj",
    foodCategory: "sarmale",
    protein: "pork",
    cookingMethods: ["baked", "stewed"],
    intensity: 4,
    fat: 4,
    salt: 3,
    acidity: 3,
    sweetness: 2,
    smoke: 1,
    spice: 2,
    sour: true,
    aliases: ["varza cluj"],
    family: "cabbage-roll",
    romanian: true,
    romanianRegion: "Transilvania",
    discoveryValue: 4,
  }),
  dish({
    id: "sarmale-de-post",
    name: "Sarmale de post",
    foodCategory: "sarmale",
    protein: "none",
    cookingMethods: ["stewed"],
    intensity: 3,
    fat: 2,
    salt: 3,
    acidity: 3,
    sweetness: 2,
    smoke: 1,
    spice: 2,
    sour: true,
    aliases: ["sarmale de post"],
    family: "cabbage-roll",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 4,
  }),
  dish({
    id: "tochitura-moldoveneasca",
    name: "Tochitura moldoveneasca",
    foodCategory: "grilled_meat",
    protein: "pork",
    cookingMethods: ["stewed", "fried"],
    intensity: 5,
    fat: 5,
    salt: 4,
    acidity: 2,
    sweetness: 1,
    smoke: 2,
    spice: 2,
    aliases: ["tochitura"],
    family: "rich-pork-stew",
    romanian: true,
    romanianRegion: "Moldova",
    discoveryValue: 5,
  }),
  dish({
    id: "pomana-porcului",
    name: "Pomana porcului",
    foodCategory: "pork",
    protein: "pork",
    cookingMethods: ["fried", "roasted"],
    intensity: 5,
    fat: 5,
    salt: 4,
    acidity: 1,
    sweetness: 1,
    smoke: 2,
    spice: 2,
    aliases: ["pomana porcului"],
    family: "rich-pork-stew",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 4,
  }),
  dish({
    id: "ciolan-afumat-cu-fasole",
    name: "Ciolan afumat cu fasole",
    foodCategory: "pork",
    protein: "pork",
    cookingMethods: ["smoked", "stewed"],
    intensity: 5,
    fat: 4,
    salt: 4,
    acidity: 2,
    sweetness: 1,
    smoke: 5,
    spice: 2,
    aliases: ["ciolan afumat"],
    family: "smoked-pork",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 4,
  }),
  dish({
    id: "fasole-cu-ciolan",
    name: "Fasole cu ciolan",
    foodCategory: "pork",
    protein: "pork",
    cookingMethods: ["stewed", "smoked"],
    intensity: 4,
    fat: 4,
    salt: 4,
    acidity: 2,
    sweetness: 1,
    smoke: 4,
    spice: 2,
    aliases: ["fasole cu ciolan"],
    family: "smoked-pork",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 3,
  }),
  dish({
    id: "carnati-afumati-cu-mamaliga",
    name: "Carnati afumati cu mamaliga",
    foodCategory: "pork",
    protein: "pork",
    cookingMethods: ["smoked", "grilled"],
    intensity: 4,
    fat: 4,
    salt: 4,
    acidity: 1,
    sweetness: 1,
    smoke: 5,
    spice: 3,
    aliases: ["carnati afumati"],
    family: "smoked-pork",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 4,
  }),
  dish({
    id: "mici",
    name: "Mici",
    foodCategory: "grilled_meat",
    protein: "beef",
    cookingMethods: ["grilled"],
    intensity: 4,
    fat: 4,
    salt: 4,
    acidity: 1,
    sweetness: 1,
    smoke: 3,
    spice: 3,
    aliases: ["mititei"],
    family: "grilled-mince",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 2,
  }),
  dish({
    id: "pastrama-de-oaie",
    name: "Pastrama de oaie",
    foodCategory: "festive_traditional",
    protein: "lamb",
    cookingMethods: ["smoked", "grilled"],
    intensity: 5,
    fat: 3,
    salt: 5,
    acidity: 1,
    sweetness: 1,
    smoke: 4,
    spice: 3,
    aliases: ["pastrama"],
    family: "cured-lamb",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 5,
  }),
  dish({
    id: "miel-la-cuptor",
    name: "Miel la cuptor",
    foodCategory: "festive_traditional",
    protein: "lamb",
    cookingMethods: ["roasted"],
    intensity: 4,
    fat: 3,
    salt: 3,
    acidity: 1,
    sweetness: 1,
    smoke: 2,
    spice: 2,
    aliases: ["miel", "carne de miel"],
    family: "roast-lamb",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 4,
  }),
  dish({
    id: "drob",
    name: "Drob",
    foodCategory: "festive_traditional",
    protein: "lamb",
    cookingMethods: ["baked"],
    intensity: 4,
    fat: 3,
    salt: 3,
    acidity: 1,
    sweetness: 1,
    smoke: 1,
    spice: 2,
    aliases: ["drob de miel"],
    family: "roast-lamb",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 4,
  }),
  dish({
    id: "rata-pe-varza",
    name: "Rata pe varza",
    foodCategory: "poultry",
    protein: "duck",
    cookingMethods: ["roasted", "stewed"],
    intensity: 4,
    fat: 5,
    salt: 3,
    acidity: 3,
    sweetness: 2,
    smoke: 1,
    spice: 2,
    sour: true,
    aliases: ["rata pe varza", "rata"],
    family: "duck",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 5,
  }),
  dish({
    id: "pui-la-ceaun",
    name: "Pui la ceaun",
    foodCategory: "poultry",
    protein: "chicken",
    cookingMethods: ["stewed", "fried"],
    intensity: 3,
    fat: 3,
    salt: 3,
    acidity: 2,
    sweetness: 1,
    smoke: 1,
    spice: 2,
    aliases: ["pui la ceaun"],
    family: "chicken-rustic",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 4,
  }),
  dish({
    id: "ostropel-de-pui",
    name: "Ostropel de pui",
    foodCategory: "poultry",
    protein: "chicken",
    cookingMethods: ["stewed"],
    intensity: 3,
    fat: 3,
    salt: 3,
    acidity: 3,
    sweetness: 2,
    smoke: 1,
    spice: 2,
    tomatoRich: true,
    aliases: ["ostropel"],
    family: "chicken-sauce",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 4,
  }),
  dish({
    id: "ciulama-de-pui",
    name: "Ciulama de pui",
    foodCategory: "poultry",
    protein: "chicken",
    cookingMethods: ["stewed"],
    intensity: 3,
    fat: 4,
    salt: 2,
    acidity: 1,
    sweetness: 1,
    smoke: 1,
    spice: 1,
    creamRich: true,
    aliases: ["ciulama"],
    family: "chicken-cream",
    romanian: true,
    romanianRegion: "Moldova",
    discoveryValue: 4,
  }),
  dish({
    id: "curcan-la-cuptor",
    name: "Curcan la cuptor",
    foodCategory: "poultry",
    protein: "turkey",
    cookingMethods: ["roasted"],
    intensity: 3,
    fat: 3,
    salt: 3,
    acidity: 1,
    sweetness: 1,
    smoke: 2,
    spice: 2,
    aliases: ["curcan"],
    family: "roast-poultry",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 3,
  }),
  dish({
    id: "iepure-la-cuptor",
    name: "Iepure la cuptor",
    foodCategory: "poultry",
    protein: "rabbit",
    cookingMethods: ["roasted"],
    intensity: 3,
    fat: 2,
    salt: 2,
    acidity: 2,
    sweetness: 1,
    smoke: 1,
    spice: 2,
    aliases: ["iepure"],
    family: "rabbit",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 5,
  }),
  dish({
    id: "tocana-de-iepure",
    name: "Tocana de iepure",
    foodCategory: "poultry",
    protein: "rabbit",
    cookingMethods: ["stewed"],
    intensity: 3,
    fat: 2,
    salt: 3,
    acidity: 2,
    sweetness: 1,
    smoke: 1,
    spice: 2,
    tomatoRich: true,
    aliases: ["tocana de iepure"],
    family: "rabbit",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 5,
  }),
  dish({
    id: "tocanita-de-vanat",
    name: "Tocanita de vanat",
    foodCategory: "game",
    protein: "game",
    cookingMethods: ["stewed"],
    intensity: 5,
    fat: 4,
    salt: 3,
    acidity: 2,
    sweetness: 1,
    smoke: 2,
    spice: 3,
    tomatoRich: true,
    aliases: [
      "tocanite de vanat",
      "tocana de vanat",
      "carne de vanat",
      "tocanita de vânat",
    ],
    family: "game-stew",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 5,
  }),
  dish({
    id: "friptura-de-vita",
    name: "Friptura de vita",
    foodCategory: "beef",
    protein: "beef",
    cookingMethods: ["roasted"],
    intensity: 4,
    fat: 3,
    salt: 3,
    acidity: 1,
    sweetness: 1,
    smoke: 2,
    spice: 1,
    aliases: ["vita la cuptor", "friptura de vita"],
    family: "roast-beef",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 2,
  }),
  dish({
    id: "saramura-de-crap",
    name: "Saramura de crap",
    foodCategory: "fish",
    protein: "fish",
    cookingMethods: ["grilled", "boiled"],
    intensity: 3,
    fat: 3,
    salt: 5,
    acidity: 4,
    sweetness: 1,
    smoke: 1,
    spice: 2,
    sour: true,
    aliases: ["saramura"],
    family: "delta-fish",
    romanian: true,
    romanianRegion: "Dobrogea",
    discoveryValue: 5,
  }),
  dish({
    id: "plachie-de-crap",
    name: "Plachie de crap",
    foodCategory: "fish",
    protein: "fish",
    cookingMethods: ["baked", "stewed"],
    intensity: 3,
    fat: 3,
    salt: 3,
    acidity: 3,
    sweetness: 1,
    smoke: 1,
    spice: 2,
    tomatoRich: true,
    aliases: ["plachie"],
    family: "delta-fish",
    romanian: true,
    romanianRegion: "Dobrogea",
    discoveryValue: 5,
  }),
  dish({
    id: "crap-prajit-cu-mamaliga",
    name: "Crap prajit cu mamaliga",
    foodCategory: "fish",
    protein: "fish",
    cookingMethods: ["fried"],
    intensity: 3,
    fat: 4,
    salt: 3,
    acidity: 2,
    sweetness: 1,
    smoke: 1,
    spice: 1,
    fried: true,
    aliases: ["crap prajit"],
    family: "fried-fish",
    romanian: true,
    romanianRegion: "Delta Dunarii",
    discoveryValue: 4,
  }),
  dish({
    id: "scrumbie-de-dunare",
    name: "Scrumbie de Dunare",
    foodCategory: "fish",
    protein: "fish",
    cookingMethods: ["grilled", "fried"],
    intensity: 3,
    fat: 4,
    salt: 3,
    acidity: 2,
    sweetness: 1,
    smoke: 1,
    spice: 1,
    aliases: ["scrumbie"],
    family: "delta-fish",
    romanian: true,
    romanianRegion: "Delta Dunarii",
    discoveryValue: 5,
  }),
  dish({
    id: "pastrav-la-gratar-cu-mamaliga",
    name: "Pastrav la gratar cu mamaliga",
    foodCategory: "grilled_fish",
    protein: "fish",
    cookingMethods: ["grilled"],
    intensity: 2,
    fat: 2,
    salt: 2,
    acidity: 3,
    sweetness: 1,
    smoke: 2,
    spice: 1,
    aliases: ["pastrav", "pastrav cu mamaliga"],
    family: "trout",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 4,
  }),
  dish({
    id: "storceag",
    name: "Storceag",
    foodCategory: "fish",
    protein: "fish",
    cookingMethods: ["stewed", "boiled"],
    intensity: 3,
    fat: 3,
    salt: 3,
    acidity: 3,
    sweetness: 1,
    smoke: 1,
    spice: 2,
    sour: true,
    aliases: ["storceag"],
    family: "delta-fish",
    romanian: true,
    romanianRegion: "Delta Dunarii",
    discoveryValue: 5,
  }),
  dish({
    id: "hamsii",
    name: "Hamsii",
    foodCategory: "fish",
    protein: "fish",
    cookingMethods: ["fried"],
    intensity: 2,
    fat: 3,
    salt: 4,
    acidity: 3,
    sweetness: 1,
    smoke: 1,
    spice: 1,
    fried: true,
    aliases: ["hamsii"],
    family: "fried-fish",
    romanian: true,
    romanianRegion: "Dobrogea",
    discoveryValue: 4,
  }),
  dish({
    id: "salata-de-icre",
    name: "Salata de icre",
    foodCategory: "fish",
    protein: "seafood",
    cookingMethods: ["raw"],
    intensity: 2,
    fat: 4,
    salt: 4,
    acidity: 3,
    sweetness: 1,
    smoke: 1,
    spice: 1,
    aliases: ["icre"],
    family: "roe",
    romanian: true,
    romanianRegion: "Dobrogea",
    discoveryValue: 5,
  }),
  dish({
    id: "peste-la-cuptor",
    name: "Peste la cuptor",
    foodCategory: "fish",
    protein: "fish",
    cookingMethods: ["baked"],
    intensity: 2,
    fat: 2,
    salt: 2,
    acidity: 2,
    sweetness: 1,
    smoke: 1,
    spice: 1,
    aliases: ["peste la cuptor"],
    family: "baked-fish",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 2,
  }),
  dish({
    id: "fructe-de-mare",
    name: "Fructe de mare",
    foodCategory: "fish",
    protein: "seafood",
    cookingMethods: ["boiled", "grilled"],
    intensity: 2,
    fat: 2,
    salt: 3,
    acidity: 3,
    sweetness: 1,
    smoke: 1,
    spice: 1,
    aliases: ["fructe de mare"],
    family: "seafood",
    romanian: false,
    romanianRegion: null,
    discoveryValue: 1,
  }),
  dish({
    id: "zacusca",
    name: "Zacusca",
    foodCategory: "vegetable",
    protein: "none",
    cookingMethods: ["baked", "stewed"],
    intensity: 3,
    fat: 3,
    salt: 3,
    acidity: 3,
    sweetness: 2,
    smoke: 2,
    spice: 2,
    tomatoRich: true,
    aliases: ["zacusca"],
    family: "vegetable-preserve",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 4,
  }),
  dish({
    id: "salata-de-vinete",
    name: "Salata de vinete",
    foodCategory: "vegetable",
    protein: "none",
    cookingMethods: ["baked"],
    intensity: 2,
    fat: 3,
    salt: 3,
    acidity: 2,
    sweetness: 1,
    smoke: 3,
    spice: 1,
    aliases: ["vinete"],
    family: "vegetable-spread",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 4,
  }),
  dish({
    id: "ciuperci-cu-mamaliga",
    name: "Ciuperci cu mamaliga",
    foodCategory: "vegetable",
    protein: "none",
    cookingMethods: ["stewed", "fried"],
    intensity: 3,
    fat: 3,
    salt: 3,
    acidity: 2,
    sweetness: 1,
    smoke: 1,
    spice: 2,
    aliases: ["ciuperci"],
    family: "mushroom",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 4,
  }),
  dish({
    id: "iahnie-de-fasole",
    name: "Iahnie de fasole",
    foodCategory: "vegetable",
    protein: "none",
    cookingMethods: ["stewed"],
    intensity: 3,
    fat: 2,
    salt: 3,
    acidity: 2,
    sweetness: 1,
    smoke: 1,
    spice: 2,
    tomatoRich: true,
    aliases: ["iahnie"],
    family: "bean-stew",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 3,
  }),
  dish({
    id: "ghiveci",
    name: "Ghiveci",
    foodCategory: "vegetable",
    protein: "none",
    cookingMethods: ["stewed"],
    intensity: 3,
    fat: 2,
    salt: 3,
    acidity: 3,
    sweetness: 2,
    smoke: 1,
    spice: 2,
    tomatoRich: true,
    aliases: ["ghiveci"],
    family: "vegetable-stew",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 3,
  }),
  dish({
    id: "ardei-copti",
    name: "Ardei copti",
    foodCategory: "vegetable",
    protein: "none",
    cookingMethods: ["baked"],
    intensity: 2,
    fat: 2,
    salt: 2,
    acidity: 3,
    sweetness: 2,
    smoke: 3,
    spice: 1,
    aliases: ["ardei copti"],
    family: "roasted-veg",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 3,
  }),
  dish({
    id: "fasole-batuta",
    name: "Fasole batuta",
    foodCategory: "vegetable",
    protein: "none",
    cookingMethods: ["boiled"],
    intensity: 2,
    fat: 3,
    salt: 3,
    acidity: 2,
    sweetness: 1,
    smoke: 1,
    spice: 1,
    aliases: ["fasole batuta"],
    family: "bean-spread",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 3,
  }),
  dish({
    id: "bulz",
    name: "Bulz",
    foodCategory: "cheese",
    protein: "none",
    cookingMethods: ["baked", "grilled"],
    intensity: 3,
    fat: 4,
    salt: 4,
    acidity: 2,
    sweetness: 1,
    smoke: 2,
    spice: 1,
    aliases: ["bulz"],
    family: "mountain-cheese",
    romanian: true,
    romanianRegion: "Transilvania",
    discoveryValue: 5,
  }),
  dish({
    id: "mamaliga-cu-branza-si-smantana",
    name: "Mamaliga cu branza si smantana",
    foodCategory: "cheese",
    protein: "none",
    cookingMethods: ["boiled"],
    intensity: 3,
    fat: 4,
    salt: 3,
    acidity: 2,
    sweetness: 1,
    smoke: 1,
    spice: 1,
    creamRich: true,
    aliases: ["mamaliga cu branza"],
    family: "mountain-cheese",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 4,
  }),
  dish({
    id: "branza-de-burduf",
    name: "Branza de burduf",
    foodCategory: "cheese",
    protein: "none",
    cookingMethods: ["fermented"],
    intensity: 4,
    fat: 4,
    salt: 5,
    acidity: 3,
    sweetness: 1,
    smoke: 1,
    spice: 1,
    aliases: ["burduf"],
    family: "aged-cheese",
    romanian: true,
    romanianRegion: "Transilvania",
    discoveryValue: 5,
  }),
  dish({
    id: "telemea",
    name: "Telemea",
    foodCategory: "cheese",
    protein: "none",
    cookingMethods: ["fermented"],
    intensity: 2,
    fat: 3,
    salt: 4,
    acidity: 3,
    sweetness: 1,
    smoke: 1,
    spice: 1,
    aliases: ["branzeturi proaspete"],
    family: "fresh-cheese",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 3,
  }),
  dish({
    id: "cascaval-maturat",
    name: "Cascaval maturat",
    foodCategory: "cheese",
    protein: "none",
    cookingMethods: ["fermented"],
    intensity: 3,
    fat: 4,
    salt: 3,
    acidity: 2,
    sweetness: 1,
    smoke: 1,
    spice: 1,
    aliases: ["branzeturi maturate", "branza matura"],
    family: "aged-cheese",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 3,
  }),
  dish({
    id: "placinta-dobrogeana",
    name: "Placinta dobrogeana",
    foodCategory: "cheese",
    protein: "none",
    cookingMethods: ["baked"],
    intensity: 3,
    fat: 4,
    salt: 3,
    acidity: 2,
    sweetness: 1,
    smoke: 1,
    spice: 1,
    aliases: ["placinta dobrogeana"],
    family: "cheese-pie",
    romanian: true,
    romanianRegion: "Dobrogea",
    discoveryValue: 5,
  }),
  dish({
    id: "cozonac",
    name: "Cozonac",
    foodCategory: "dessert",
    protein: "none",
    cookingMethods: ["baked"],
    intensity: 3,
    fat: 3,
    salt: 1,
    acidity: 1,
    sweetness: 5,
    smoke: 1,
    spice: 2,
    aliases: ["cozonac"],
    family: "sweet-bread",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 4,
  }),
  dish({
    id: "pasca",
    name: "Pasca",
    foodCategory: "dessert",
    protein: "none",
    cookingMethods: ["baked"],
    intensity: 3,
    fat: 3,
    salt: 1,
    acidity: 2,
    sweetness: 4,
    smoke: 1,
    spice: 1,
    aliases: ["pasca"],
    family: "sweet-cheese",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 4,
  }),
  dish({
    id: "papanasi",
    name: "Papanasi",
    foodCategory: "dessert",
    protein: "none",
    cookingMethods: ["fried"],
    intensity: 3,
    fat: 4,
    salt: 1,
    acidity: 2,
    sweetness: 5,
    smoke: 1,
    spice: 1,
    fried: true,
    aliases: ["papanasi"],
    family: "fried-dessert",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 4,
  }),
  dish({
    id: "poale-n-brau",
    name: "Poale-n brau",
    foodCategory: "dessert",
    protein: "none",
    cookingMethods: ["baked"],
    intensity: 3,
    fat: 3,
    salt: 1,
    acidity: 2,
    sweetness: 4,
    smoke: 1,
    spice: 1,
    aliases: ["poale in brau"],
    family: "sweet-cheese",
    romanian: true,
    romanianRegion: "Moldova",
    discoveryValue: 5,
  }),
  dish({
    id: "alivenci",
    name: "Alivenci",
    foodCategory: "dessert",
    protein: "none",
    cookingMethods: ["baked"],
    intensity: 3,
    fat: 3,
    salt: 1,
    acidity: 2,
    sweetness: 4,
    smoke: 1,
    spice: 1,
    aliases: ["alivenci"],
    family: "sweet-cheese",
    romanian: true,
    romanianRegion: "Moldova",
    discoveryValue: 5,
  }),
  dish({
    id: "placinta-cu-mere",
    name: "Placinta cu mere",
    foodCategory: "dessert",
    protein: "none",
    cookingMethods: ["baked"],
    intensity: 2,
    fat: 2,
    salt: 1,
    acidity: 3,
    sweetness: 4,
    smoke: 1,
    spice: 2,
    aliases: ["placinta cu mere"],
    family: "fruit-pie",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 3,
  }),
  dish({
    id: "placinta-cu-dovleac",
    name: "Placinta cu dovleac",
    foodCategory: "dessert",
    protein: "none",
    cookingMethods: ["baked"],
    intensity: 2,
    fat: 2,
    salt: 1,
    acidity: 1,
    sweetness: 4,
    smoke: 1,
    spice: 2,
    aliases: ["placinta cu dovleac"],
    family: "fruit-pie",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 4,
  }),
  dish({
    id: "clatite-cu-dulceata",
    name: "Clatite cu dulceata",
    foodCategory: "dessert",
    protein: "none",
    cookingMethods: ["fried"],
    intensity: 2,
    fat: 3,
    salt: 1,
    acidity: 2,
    sweetness: 5,
    smoke: 1,
    spice: 1,
    fried: true,
    aliases: ["clatite"],
    family: "fruit-dessert",
    romanian: true,
    romanianRegion: null,
    discoveryValue: 2,
  }),
  dish({
    id: "aperitive",
    name: "Aperitive",
    foodCategory: "vegetable",
    protein: "none",
    cookingMethods: ["raw"],
    intensity: 2,
    fat: 2,
    salt: 2,
    acidity: 2,
    sweetness: 1,
    smoke: 1,
    spice: 1,
    aliases: ["aperitive"],
    family: "starter",
    romanian: false,
    romanianRegion: null,
    discoveryValue: 1,
  }),
  dish({
    id: "paste-cu-ragu",
    name: "Paste cu ragu",
    foodCategory: "pasta",
    protein: "beef",
    cookingMethods: ["stewed"],
    intensity: 4,
    fat: 4,
    salt: 3,
    acidity: 3,
    sweetness: 2,
    smoke: 1,
    spice: 2,
    tomatoRich: true,
    aliases: ["paste", "ragu"],
    family: "pasta",
    romanian: false,
    romanianRegion: null,
    discoveryValue: 1,
  }),
];

const BY_ID = new Map(ROMANIAN_DISHES.map((item) => [item.id, item]));

export function foldDishName(value: string): string {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/\s+/g, " ")
    .trim();
}

export function findRomanianDishByName(name: string): RomanianDishProfile | null {
  const folded = foldDishName(name);
  return (
    ROMANIAN_DISHES.find(
      (item) =>
        foldDishName(item.name) === folded ||
        item.aliases.some((alias) => foldDishName(alias) === folded) ||
        item.id === folded,
    ) ?? null
  );
}

export function getRomanianDishById(id: string): RomanianDishProfile | null {
  return BY_ID.get(id) ?? null;
}

export function dishesInFamily(family: string): RomanianDishProfile[] {
  return ROMANIAN_DISHES.filter((item) => item.family === family);
}
