import "./load-env";
import { db } from "./db";
import {
  grapeVarieties,
  regions,
  wineries,
  wines,
  type AffiliateLink,
  type AvailabilityEntry,
  type FoodPairing,
  type GrapeVarietyShare,
} from "./schema";
import { buildWineImageAlt } from "./wine-images";

interface WineSeed {
  slug: string;
  name: string;
  winerySlug: string;
  regionSlug: string;
  type: "red" | "white" | "rose" | "sparkling" | "dessert" | "orange";
  sweetness?: "sec" | "demisec" | "demidulce" | "dulce";
  vintage: number;
  grapeVarieties: GrapeVarietyShare[];
  alcohol: number;
  sugar: number;
  acidity: number;
  priceAvg: number;
  valueScore: number;
  giftScore: number;
  foodMatchScore: number;
  beginnerFriendly: boolean;
  cellarPotential: number;
  overpricedRisk: "low" | "medium" | "high";
  tastingNotes: string;
  foodPairings: FoodPairing[];
  ratingAvg: number;
  ratingCount: number;
  imageUrl?: string;
  imageAlt?: string;
}

const regionSeed = [
  {
    slug: "dealu-mare",
    name: "Dealu Mare",
    description:
      "Cea mai renumita regiune pentru vinuri rosii din Romania, pe versantii sudici ai Carpatilor de Curbura.",
  },
  {
    slug: "dragasani",
    name: "Dragasani",
    description:
      "Regiune dinamica de pe malul Oltului, apreciata pentru soiuri autohtone si vinuri elegante.",
  },
  {
    slug: "cotnari",
    name: "Cotnari",
    description:
      "Podgorie istorica din Moldova, faimoasa pentru vinurile dulci si soiul Grasa de Cotnari.",
  },
  {
    slug: "recas",
    name: "Recas",
    description:
      "Una dintre cele mai mari podgorii din vestul tarii, cu un raport calitate-pret excelent.",
  },
  {
    slug: "murfatlar",
    name: "Murfatlar",
    description:
      "Podgorie din Dobrogea, cu un climat insorit ideal pentru vinuri albe aromate si dulci.",
  },
  {
    slug: "lechinta",
    name: "Lechinta",
    description:
      "Podgorie transilvaneana cu altitudine ridicata, recunoscuta pentru prospetime si aciditate.",
  },
  {
    slug: "oltenia",
    name: "Oltenia",
    description:
      "Dealurile insorite ale Olteniei, cu vinuri rosii corpolente si soiuri internationale.",
  },
  {
    slug: "segarcea",
    name: "Segarcea",
    description:
      "Domeniu istoric regal din sudul Olteniei, cu un climat cald si vinuri rosii si albe expresive.",
  },
  {
    slug: "banat",
    name: "Banat",
    description:
      "Podgorie din vestul tarii, cu influente central-europene si vinuri elegante, proaspete.",
  },
  {
    slug: "vrancea",
    name: "Vrancea",
    description:
      "Cea mai mare zona viticola din Romania ca suprafata, cu vinuri variate si accesibile.",
  },
  {
    slug: "tarnave",
    name: "Tarnave",
    description:
      "Podgorie transilvaneana de altitudine, recunoscuta pentru vinuri albe aromate si spumante.",
  },
  {
    slug: "samburesti",
    name: "Samburesti",
    description:
      "Zona din Oltenia faimoasa pentru Cabernet Sauvignon corpolent si structurat.",
  },
  {
    slug: "minis",
    name: "Minis",
    description:
      "Podgorie istorica din vestul Romaniei, leagan al soiului autohton Cadarca.",
  },
];

const grapeSeed: {
  slug: string;
  name: string;
  color: "red" | "white" | "rose";
  isIndigenous: boolean;
  description: string;
}[] = [
  {
    slug: "feteasca-neagra",
    name: "Feteasca Neagra",
    color: "red",
    isIndigenous: true,
    description:
      "Soiul rosu emblematic al Romaniei, cu arome de prune uscate si condimente.",
  },
  {
    slug: "feteasca-alba",
    name: "Feteasca Alba",
    color: "white",
    isIndigenous: true,
    description: "Soi alb autohton, floral si delicat, cu aciditate echilibrata.",
  },
  {
    slug: "tamaioasa-romaneasca",
    name: "Tamaioasa Romaneasca",
    color: "white",
    isIndigenous: true,
    description: "Soi aromat cu note de busuioc, miere si flori de tei.",
  },
  {
    slug: "grasa-de-cotnari",
    name: "Grasa de Cotnari",
    color: "white",
    isIndigenous: true,
    description: "Soi nobil din Cotnari, ideal pentru vinuri dulci de exceptie.",
  },
  {
    slug: "cabernet-sauvignon",
    name: "Cabernet Sauvignon",
    color: "red",
    isIndigenous: false,
    description: "Soi international corpolent, cu taninuri ferme si potential de invechire.",
  },
  {
    slug: "merlot",
    name: "Merlot",
    color: "red",
    isIndigenous: false,
    description: "Soi rosu catifelat, cu fructe rosii coapte si taninuri fine.",
  },
  {
    slug: "chardonnay",
    name: "Chardonnay",
    color: "white",
    isIndigenous: false,
    description: "Soi alb versatil, de la prospetime minerala la note de unt si vanilie.",
  },
  {
    slug: "feteasca-regala",
    name: "Feteasca Regala",
    color: "white",
    isIndigenous: true,
    description:
      "Soi autohton creat in Transilvania, proaspat si echilibrat, cu note de mar verde si flori.",
  },
  {
    slug: "cramposie-selectionata",
    name: "Cramposie Selectionata",
    color: "white",
    isIndigenous: true,
    description:
      "Soi alb din Dragasani, vioi si citric, cu o aciditate crocanta si prospetime.",
  },
  {
    slug: "negru-de-dragasani",
    name: "Negru de Dragasani",
    color: "red",
    isIndigenous: true,
    description:
      "Soi rosu autohton din Dragasani, condimentat, cu fructe negre si taninuri ferme.",
  },
  {
    slug: "novac",
    name: "Novac",
    color: "red",
    isIndigenous: true,
    description:
      "Soi rosu oltenesc, suculent si fructat, cu note de mure si piper.",
  },
  {
    slug: "busuioaca-de-bohotin",
    name: "Busuioaca de Bohotin",
    color: "rose",
    isIndigenous: true,
    description:
      "Soi aromat unic, cu petale de trandafir si busuioc, folosit pentru roze parfumate.",
  },
  {
    slug: "cadarca",
    name: "Cadarca",
    color: "red",
    isIndigenous: true,
    description:
      "Soi rosu istoric din Minis, usor pana la mediu, cu fructe rosii si condimente.",
  },
  {
    slug: "pinot-noir",
    name: "Pinot Noir",
    color: "red",
    isIndigenous: false,
    description:
      "Soi rosu elegant si fin, cu fructe rosii, note de pamant si taninuri delicate.",
  },
  {
    slug: "syrah",
    name: "Syrah",
    color: "red",
    isIndigenous: false,
    description:
      "Soi rosu generos, cu fructe negre coapte, piper si o structura ampla.",
  },
  {
    slug: "sauvignon-blanc",
    name: "Sauvignon Blanc",
    color: "white",
    isIndigenous: false,
    description:
      "Soi alb aromat, cu prospetime citrica, note herbacee si de fructul pasiunii.",
  },
  {
    slug: "riesling",
    name: "Riesling",
    color: "white",
    isIndigenous: false,
    description:
      "Soi alb nobil, cu aciditate vie, note de citrice, piersica si mineralitate.",
  },
  {
    slug: "pinot-gris",
    name: "Pinot Gris",
    color: "white",
    isIndigenous: false,
    description:
      "Soi alb cu corp mediu, fructe albe coapte, miere fina si textura catifelata.",
  },
];

const winerySeed = [
  {
    slug: "davino",
    name: "Davino",
    regionSlug: "dealu-mare",
    verified: false,
    foundedYear: 1991,
    website: "https://davino.ro",
    description:
      "Una dintre cramele de referinta din Romania, pionier al vinurilor premium din Dealu Mare.",
  },
  {
    slug: "serve",
    name: "SERVE",
    regionSlug: "dealu-mare",
    verified: false,
    foundedYear: 1994,
    website: "https://serve.ro",
    description:
      "Prima crama privata cu capital strain din Romania, fondata de contele Guy de Poix.",
  },
  {
    slug: "avincis",
    name: "Avincis",
    regionSlug: "dragasani",
    verified: false,
    foundedYear: 2007,
    website: "https://avincis.ro",
    description:
      "Crama boutique din Dragasani, cu accent pe soiuri autohtone si arhitectura premiata.",
  },
  {
    slug: "crama-oprisor",
    name: "Crama Oprisor",
    regionSlug: "oltenia",
    verified: false,
    foundedYear: 2002,
    website: "https://cramaoprisor.ro",
    description:
      "Crama din Mehedinti cunoscuta pentru gama La Cetate si Smerenie, parte din grupul Carl Reh.",
  },
  {
    slug: "liliac",
    name: "Liliac",
    regionSlug: "lechinta",
    verified: false,
    foundedYear: 2010,
    website: "https://liliac.com",
    description:
      "Crama transilvaneana din Lechinta, cu vinuri elegante si proaspete de altitudine.",
  },
  {
    slug: "cramele-recas",
    name: "Cramele Recas",
    regionSlug: "recas",
    verified: false,
    foundedYear: 1991,
    website: "https://cramelerecas.ro",
    description:
      "Cel mai mare exportator de vin din Romania, cu un raport calitate-pret remarcabil.",
  },
  {
    slug: "casa-de-vinuri-cotnari",
    name: "Casa de Vinuri Cotnari",
    regionSlug: "cotnari",
    verified: false,
    foundedYear: 2007,
    website: "https://casadevinuricotnari.ro",
    description:
      "Producator modern din Cotnari, dedicat soiurilor autohtone si vinurilor dulci.",
  },
  {
    slug: "budureasca",
    name: "Budureasca",
    regionSlug: "dealu-mare",
    verified: false,
    foundedYear: 2009,
    website: "https://budureasca.ro",
    description:
      "Crama din Valea Calugareasca, in inima podgoriei Dealu Mare, cu o gama larga premiata.",
  },
  {
    slug: "domeniile-coroanei-segarcea",
    name: "Domeniile Coroanei Segarcea",
    regionSlug: "segarcea",
    verified: false,
    foundedYear: 1906,
    website: "https://domeniulcoroanei.ro",
    description:
      "Domeniu regal istoric din Segarcea, cu o traditie de peste un secol si vinuri premiate.",
  },
  {
    slug: "tohani",
    name: "Tohani",
    regionSlug: "dealu-mare",
    verified: false,
    foundedYear: 1968,
    website: "https://tohani.ro",
    description:
      "Una dintre cele mai cunoscute crame din Dealu Mare, cu o gama variata pentru toate gusturile.",
  },
  {
    slug: "petro-vaselo",
    name: "Petro Vaselo",
    regionSlug: "banat",
    verified: false,
    foundedYear: 2004,
    website: "https://petrovaselo.com",
    description:
      "Crama boutique din Banat, cu accent pe spumante metoda traditionala si soiuri autohtone.",
  },
  {
    slug: "crama-girboiu",
    name: "Crama Girboiu",
    regionSlug: "vrancea",
    verified: false,
    foundedYear: 2007,
    website: "https://cramagirboiu.ro",
    description:
      "Crama de familie din Vrancea, dedicata soiurilor autohtone si terroir-ului local.",
  },
  {
    slug: "lacerta",
    name: "Lacerta",
    regionSlug: "dealu-mare",
    verified: false,
    foundedYear: 2007,
    website: "https://lacertawinery.ro",
    description:
      "Crama moderna din Dealu Mare, cu vinuri echilibrate si cuvee-uri premiate international.",
  },
  {
    slug: "crama-basilescu",
    name: "Crama Basilescu",
    regionSlug: "dealu-mare",
    verified: false,
    foundedYear: 2015,
    website: "https://cramabasilescu.ro",
    description:
      "Crama din Urlati, axata pe vinificatie sustenabila si soiuri romanesti aromate.",
  },
  {
    slug: "jidvei",
    name: "Jidvei",
    regionSlug: "tarnave",
    verified: false,
    foundedYear: 1949,
    website: "https://jidvei.ro",
    description:
      "Cel mai mare producator de vinuri albe din Romania, in podgoria Tarnave din Transilvania.",
  },
  {
    slug: "domeniile-samburesti",
    name: "Domeniile Samburesti",
    regionSlug: "samburesti",
    verified: false,
    foundedYear: 2000,
    website: "https://domeniilesamburesti.ro",
    description:
      "Producator oltenesc renumit pentru Cabernet Sauvignon corpolent din terroir-ul Samburesti.",
  },
  {
    slug: "balla-geza",
    name: "Balla Geza",
    regionSlug: "minis",
    verified: false,
    foundedYear: 1999,
    website: "https://www.ballageza.com",
    description:
      "Crama din Minis, specializata in soiul autohton Cadarca si vinuri de pe terase de piatra.",
  },
  {
    slug: "corcova",
    name: "Corcova Roy & Dâmboviceanu",
    regionSlug: "oltenia",
    verified: false,
    foundedYear: 2005,
    website: "https://corcova.ro",
    description:
      "Domeniu din Mehedinti cu traditie franceza, apreciat pentru Pinot Noir si vinuri elegante.",
  },
  {
    slug: "prince-stirbey",
    name: "Prince Stirbey",
    regionSlug: "dragasani",
    verified: false,
    foundedYear: 2004,
    website: "https://stirbey.com",
    description:
      "Crama aristocrata din Dragasani, pionier al soiurilor autohtone Cramposie, Novac si Negru.",
  },
  {
    slug: "vinarte",
    name: "Vinarte",
    regionSlug: "dealu-mare",
    verified: false,
    foundedYear: 1998,
    website: "https://vinarte.ro",
    description:
      "Producator cu domenii in mai multe podgorii, cunoscut pentru gama premium Prince Matei.",
  },
  {
    slug: "halewood",
    name: "Halewood Wines",
    regionSlug: "dealu-mare",
    verified: false,
    foundedYear: 1998,
    website: "https://halewood.com.ro",
    description:
      "Crama cu capital britanic din Dealu Mare, cu vinuri accesibile si gama Hyperion premium.",
  },
  {
    slug: "villa-vinea",
    name: "Villa Vinea",
    regionSlug: "tarnave",
    verified: false,
    foundedYear: 2006,
    website: "https://villavinea.com",
    description:
      "Crama transilvaneana de altitudine, cu vinuri albe si rosii rafinate de inspiratie central-europeana.",
  },
];

const wineSeed: WineSeed[] = [
  {
    slug: "davino-domaine-ceptura-rosu-2019",
    name: "Domaine Ceptura Rosu",
    winerySlug: "davino",
    regionSlug: "dealu-mare",
    type: "red",
    sweetness: "sec",
    vintage: 2019,
    grapeVarieties: [
      { name: "Feteasca Neagra", slug: "feteasca-neagra", percentage: 40 },
      { name: "Cabernet Sauvignon", slug: "cabernet-sauvignon", percentage: 35 },
      { name: "Merlot", slug: "merlot", percentage: 25 },
    ],
    alcohol: 14,
    sugar: 3.2,
    acidity: 5.4,
    priceAvg: 119,
    valueScore: 90,
    giftScore: 88,
    foodMatchScore: 92,
    beginnerFriendly: false,
    cellarPotential: 8,
    overpricedRisk: "low",
    tastingNotes:
      "Corpolent si elegant, cu prune uscate, vișine negre, condimente si un final lung, mineral.",
    foodPairings: [
      { dish: "Friptura de vita", score: 95 },
      { dish: "Sarmale cu mamaliga", score: 90 },
      { dish: "Branzeturi maturate", score: 85 },
    ],
    ratingAvg: 4.6,
    ratingCount: 312,
  },
  {
    slug: "davino-faimos-alb-2021",
    name: "Faimos Alb",
    winerySlug: "davino",
    regionSlug: "dealu-mare",
    type: "white",
    sweetness: "sec",
    vintage: 2021,
    grapeVarieties: [
      { name: "Feteasca Alba", slug: "feteasca-alba", percentage: 60 },
      { name: "Chardonnay", slug: "chardonnay", percentage: 40 },
    ],
    alcohol: 13.5,
    sugar: 2.5,
    acidity: 6,
    priceAvg: 72,
    valueScore: 86,
    giftScore: 78,
    foodMatchScore: 84,
    beginnerFriendly: true,
    cellarPotential: 4,
    overpricedRisk: "low",
    tastingNotes:
      "Proaspat si rafinat, cu flori albe, mar verde si o textura cremoasa.",
    foodPairings: [
      { dish: "Peste la gratar", score: 90 },
      { dish: "Pui cu legume", score: 86 },
      { dish: "Risotto cu ciuperci", score: 82 },
    ],
    ratingAvg: 4.4,
    ratingCount: 187,
  },
  {
    slug: "serve-cuvee-charlotte-2018",
    name: "Terra Romana Cuvee Charlotte",
    winerySlug: "serve",
    regionSlug: "dealu-mare",
    type: "red",
    sweetness: "sec",
    vintage: 2018,
    grapeVarieties: [
      { name: "Cabernet Sauvignon", slug: "cabernet-sauvignon", percentage: 50 },
      { name: "Merlot", slug: "merlot", percentage: 30 },
      { name: "Feteasca Neagra", slug: "feteasca-neagra", percentage: 20 },
    ],
    alcohol: 14.5,
    sugar: 3,
    acidity: 5.2,
    priceAvg: 98,
    valueScore: 84,
    giftScore: 90,
    foodMatchScore: 88,
    beginnerFriendly: false,
    cellarPotential: 10,
    overpricedRisk: "medium",
    tastingNotes:
      "Amplu si structurat, cu coacaze negre, tutun, cedru si taninuri ferme.",
    foodPairings: [
      { dish: "Mușchi de porc la cuptor", score: 92 },
      { dish: "Mici cu mustar", score: 84 },
      { dish: "Tocana de vita", score: 90 },
    ],
    ratingAvg: 4.5,
    ratingCount: 264,
  },
  {
    slug: "serve-vinul-cavalerului-feteasca-neagra-2021",
    name: "Vinul Cavalerului Feteasca Neagra",
    winerySlug: "serve",
    regionSlug: "dealu-mare",
    type: "red",
    sweetness: "sec",
    vintage: 2021,
    grapeVarieties: [
      { name: "Feteasca Neagra", slug: "feteasca-neagra", percentage: 100 },
    ],
    alcohol: 13.5,
    sugar: 4,
    acidity: 5.5,
    priceAvg: 44,
    valueScore: 89,
    giftScore: 70,
    foodMatchScore: 90,
    beginnerFriendly: true,
    cellarPotential: 4,
    overpricedRisk: "low",
    tastingNotes:
      "Accesibil si fructat, cu prune, cireșe si o nota fina de piper.",
    foodPairings: [
      { dish: "Sarmale", score: 94 },
      { dish: "Gratar de porc", score: 90 },
      { dish: "Caș si telemea", score: 80 },
    ],
    ratingAvg: 4.3,
    ratingCount: 421,
  },
  {
    slug: "avincis-cuvee-petit-2020",
    name: "Cuvee Petit Rosu",
    winerySlug: "avincis",
    regionSlug: "dragasani",
    type: "red",
    sweetness: "sec",
    vintage: 2020,
    grapeVarieties: [
      { name: "Merlot", slug: "merlot", percentage: 50 },
      { name: "Cabernet Sauvignon", slug: "cabernet-sauvignon", percentage: 50 },
    ],
    alcohol: 14,
    sugar: 3.5,
    acidity: 5.3,
    priceAvg: 56,
    valueScore: 85,
    giftScore: 72,
    foodMatchScore: 86,
    beginnerFriendly: true,
    cellarPotential: 5,
    overpricedRisk: "low",
    tastingNotes:
      "Catifelat si echilibrat, cu fructe rosii coapte si un final usor mentolat.",
    foodPairings: [
      { dish: "Pizza", score: 84 },
      { dish: "Friptura de pui", score: 86 },
      { dish: "Paste bolognese", score: 88 },
    ],
    ratingAvg: 4.2,
    ratingCount: 156,
  },
  {
    slug: "avincis-mariana-tamaioasa-2022",
    name: "Mariana Tamaioasa Romaneasca",
    winerySlug: "avincis",
    regionSlug: "dragasani",
    type: "white",
    sweetness: "demisec",
    vintage: 2022,
    grapeVarieties: [
      { name: "Tamaioasa Romaneasca", slug: "tamaioasa-romaneasca", percentage: 100 },
    ],
    alcohol: 13,
    sugar: 12,
    acidity: 6.2,
    priceAvg: 62,
    valueScore: 83,
    giftScore: 80,
    foodMatchScore: 82,
    beginnerFriendly: true,
    cellarPotential: 3,
    overpricedRisk: "low",
    tastingNotes:
      "Intens aromat, cu flori de tei, busuioc si miere, echilibrat de o aciditate vie.",
    foodPairings: [
      { dish: "Desert cu fructe", score: 88 },
      { dish: "Branza albastra", score: 84 },
      { dish: "Mancare thailandeza picanta", score: 80 },
    ],
    ratingAvg: 4.4,
    ratingCount: 142,
  },
  {
    slug: "crama-oprisor-la-cetate-cabernet-2020",
    name: "La Cetate Cabernet Sauvignon",
    winerySlug: "crama-oprisor",
    regionSlug: "oltenia",
    type: "red",
    sweetness: "sec",
    vintage: 2020,
    grapeVarieties: [
      { name: "Cabernet Sauvignon", slug: "cabernet-sauvignon", percentage: 100 },
    ],
    alcohol: 14,
    sugar: 3,
    acidity: 5.4,
    priceAvg: 39,
    valueScore: 88,
    giftScore: 66,
    foodMatchScore: 85,
    beginnerFriendly: true,
    cellarPotential: 6,
    overpricedRisk: "low",
    tastingNotes:
      "Generos si fructat, cu coacaze negre, vanilie si taninuri rotunde.",
    foodPairings: [
      { dish: "Gratar mixt", score: 90 },
      { dish: "Burger de vita", score: 88 },
      { dish: "Cașcaval la gratar", score: 78 },
    ],
    ratingAvg: 4.1,
    ratingCount: 389,
  },
  {
    slug: "liliac-feteasca-neagra-2020",
    name: "Liliac Feteasca Neagra",
    winerySlug: "liliac",
    regionSlug: "lechinta",
    type: "red",
    sweetness: "sec",
    vintage: 2020,
    grapeVarieties: [
      { name: "Feteasca Neagra", slug: "feteasca-neagra", percentage: 100 },
    ],
    alcohol: 13.5,
    sugar: 3.8,
    acidity: 5.8,
    priceAvg: 52,
    valueScore: 84,
    giftScore: 76,
    foodMatchScore: 87,
    beginnerFriendly: false,
    cellarPotential: 5,
    overpricedRisk: "low",
    tastingNotes:
      "Proaspat si elegant, cu vișine, prune si un profil mai racoros de altitudine.",
    foodPairings: [
      { dish: "Rata cu varza", score: 90 },
      { dish: "Sarmale", score: 88 },
      { dish: "Ciuperci la gratar", score: 80 },
    ],
    ratingAvg: 4.3,
    ratingCount: 173,
  },
  {
    slug: "cramele-recas-solo-quinta-2021",
    name: "Solo Quinta",
    winerySlug: "cramele-recas",
    regionSlug: "recas",
    type: "red",
    sweetness: "sec",
    vintage: 2021,
    grapeVarieties: [
      { name: "Cabernet Sauvignon", slug: "cabernet-sauvignon", percentage: 40 },
      { name: "Merlot", slug: "merlot", percentage: 35 },
      { name: "Feteasca Neagra", slug: "feteasca-neagra", percentage: 25 },
    ],
    alcohol: 14,
    sugar: 5,
    acidity: 5.2,
    priceAvg: 34,
    valueScore: 91,
    giftScore: 64,
    foodMatchScore: 86,
    beginnerFriendly: true,
    cellarPotential: 4,
    overpricedRisk: "low",
    tastingNotes:
      "Rotund si accesibil, cu fructe de padure, ciocolata si taninuri moi.",
    foodPairings: [
      { dish: "Mici", score: 90 },
      { dish: "Pizza", score: 86 },
      { dish: "Tocanita de cartofi", score: 82 },
    ],
    ratingAvg: 4.2,
    ratingCount: 512,
  },
  {
    slug: "cramele-recas-sole-chardonnay-2022",
    name: "Sole Chardonnay",
    winerySlug: "cramele-recas",
    regionSlug: "recas",
    type: "white",
    sweetness: "sec",
    vintage: 2022,
    grapeVarieties: [
      { name: "Chardonnay", slug: "chardonnay", percentage: 100 },
    ],
    alcohol: 14,
    sugar: 4,
    acidity: 5.6,
    priceAvg: 46,
    valueScore: 85,
    giftScore: 72,
    foodMatchScore: 83,
    beginnerFriendly: true,
    cellarPotential: 4,
    overpricedRisk: "low",
    tastingNotes:
      "Bogat si cremos, cu fructe galbene coapte, unt si o nota de vanilie de la baric.",
    foodPairings: [
      { dish: "Paste cu smantana", score: 88 },
      { dish: "Pui la cuptor", score: 86 },
      { dish: "Somon", score: 84 },
    ],
    ratingAvg: 4.3,
    ratingCount: 298,
  },
  {
    slug: "casa-de-vinuri-cotnari-grasa-2019",
    name: "Grasa de Cotnari",
    winerySlug: "casa-de-vinuri-cotnari",
    regionSlug: "cotnari",
    type: "dessert",
    sweetness: "dulce",
    vintage: 2019,
    grapeVarieties: [
      { name: "Grasa de Cotnari", slug: "grasa-de-cotnari", percentage: 100 },
    ],
    alcohol: 12,
    sugar: 120,
    acidity: 7,
    priceAvg: 38,
    valueScore: 82,
    giftScore: 74,
    foodMatchScore: 80,
    beginnerFriendly: true,
    cellarPotential: 8,
    overpricedRisk: "low",
    tastingNotes:
      "Dulce si nobil, cu miere, caise confiate si o aciditate care echilibreaza totul.",
    foodPairings: [
      { dish: "Cozonac", score: 90 },
      { dish: "Foie gras", score: 86 },
      { dish: "Branza cu mucegai", score: 84 },
    ],
    ratingAvg: 4.1,
    ratingCount: 134,
  },
  {
    slug: "budureasca-premium-feteasca-alba-2022",
    name: "Premium Feteasca Alba",
    winerySlug: "budureasca",
    regionSlug: "dealu-mare",
    type: "white",
    sweetness: "sec",
    vintage: 2022,
    grapeVarieties: [
      { name: "Feteasca Alba", slug: "feteasca-alba", percentage: 100 },
    ],
    alcohol: 13,
    sugar: 3,
    acidity: 6.1,
    priceAvg: 42,
    valueScore: 86,
    giftScore: 68,
    foodMatchScore: 82,
    beginnerFriendly: true,
    cellarPotential: 3,
    overpricedRisk: "low",
    tastingNotes:
      "Floral si proaspat, cu mar, pere si o mineralitate fina.",
    foodPairings: [
      { dish: "Salata de cruditati", score: 84 },
      { dish: "Peste alb", score: 86 },
      { dish: "Branza proaspata", score: 80 },
    ],
    ratingAvg: 4.0,
    ratingCount: 211,
  },
  {
    slug: "dcs-cabernet-sauvignon-prestige-2021",
    name: "Prestige Cabernet Sauvignon",
    winerySlug: "domeniile-coroanei-segarcea",
    regionSlug: "segarcea",
    type: "red",
    sweetness: "sec",
    vintage: 2021,
    grapeVarieties: [
      { name: "Cabernet Sauvignon", slug: "cabernet-sauvignon", percentage: 100 },
    ],
    alcohol: 14,
    sugar: 3.4,
    acidity: 5.3,
    priceAvg: 58,
    valueScore: 86,
    giftScore: 74,
    foodMatchScore: 87,
    beginnerFriendly: false,
    cellarPotential: 7,
    overpricedRisk: "low",
    tastingNotes:
      "Corpolent si cald, cu coacaze negre, ardei copt, cedru si taninuri ferme.",
    foodPairings: [
      { dish: "Friptura de vita", score: 92 },
      { dish: "Tochitura", score: 86 },
      { dish: "Branzeturi maturate", score: 84 },
    ],
    ratingAvg: 4.3,
    ratingCount: 198,
  },
  {
    slug: "dcs-tamaioasa-roz-2022",
    name: "Minima Moralia Tamaioasa Roz",
    winerySlug: "domeniile-coroanei-segarcea",
    regionSlug: "segarcea",
    type: "white",
    sweetness: "demisec",
    vintage: 2022,
    grapeVarieties: [
      { name: "Tamaioasa Romaneasca", slug: "tamaioasa-romaneasca", percentage: 100 },
    ],
    alcohol: 13,
    sugar: 14,
    acidity: 6,
    priceAvg: 49,
    valueScore: 83,
    giftScore: 76,
    foodMatchScore: 80,
    beginnerFriendly: true,
    cellarPotential: 3,
    overpricedRisk: "low",
    tastingNotes:
      "Parfumat si catifelat, cu flori de tei, struguri muscat si miere usoara.",
    foodPairings: [
      { dish: "Tarta cu fructe", score: 86 },
      { dish: "Branza cu mucegai", score: 82 },
      { dish: "Mancare asiatica picanta", score: 80 },
    ],
    ratingAvg: 4.2,
    ratingCount: 145,
  },
  {
    slug: "dcs-syrah-2020",
    name: "Minima Moralia Syrah",
    winerySlug: "domeniile-coroanei-segarcea",
    regionSlug: "segarcea",
    type: "red",
    sweetness: "sec",
    vintage: 2020,
    grapeVarieties: [
      { name: "Syrah", slug: "syrah", percentage: 100 },
    ],
    alcohol: 14.5,
    sugar: 3,
    acidity: 5.2,
    priceAvg: 84,
    valueScore: 84,
    giftScore: 82,
    foodMatchScore: 88,
    beginnerFriendly: false,
    cellarPotential: 8,
    overpricedRisk: "medium",
    tastingNotes:
      "Generos si condimentat, cu mure, piper negru, masline si un final afumat.",
    foodPairings: [
      { dish: "Coaste de porc", score: 92 },
      { dish: "Mici", score: 88 },
      { dish: "Vanat", score: 90 },
    ],
    ratingAvg: 4.4,
    ratingCount: 167,
  },
  {
    slug: "tohani-feteasca-neagra-rezerva-2020",
    name: "Tohani Rezerva Feteasca Neagra",
    winerySlug: "tohani",
    regionSlug: "dealu-mare",
    type: "red",
    sweetness: "sec",
    vintage: 2020,
    grapeVarieties: [
      { name: "Feteasca Neagra", slug: "feteasca-neagra", percentage: 100 },
    ],
    alcohol: 14,
    sugar: 4,
    acidity: 5.4,
    priceAvg: 47,
    valueScore: 85,
    giftScore: 72,
    foodMatchScore: 89,
    beginnerFriendly: true,
    cellarPotential: 5,
    overpricedRisk: "low",
    tastingNotes:
      "Fructat si rotund, cu prune coapte, visine si o nota fina de vanilie.",
    foodPairings: [
      { dish: "Sarmale", score: 92 },
      { dish: "Gratar de porc", score: 88 },
      { dish: "Ciorba de burta", score: 78 },
    ],
    ratingAvg: 4.1,
    ratingCount: 276,
  },
  {
    slug: "tohani-busuioaca-de-bohotin-2022",
    name: "Tohani Busuioaca de Bohotin",
    winerySlug: "tohani",
    regionSlug: "dealu-mare",
    type: "rose",
    sweetness: "demidulce",
    vintage: 2022,
    grapeVarieties: [
      { name: "Busuioaca de Bohotin", slug: "busuioaca-de-bohotin", percentage: 100 },
    ],
    alcohol: 12.5,
    sugar: 18,
    acidity: 6.2,
    priceAvg: 36,
    valueScore: 82,
    giftScore: 70,
    foodMatchScore: 78,
    beginnerFriendly: true,
    cellarPotential: 2,
    overpricedRisk: "low",
    tastingNotes:
      "Aromat si seducator, cu petale de trandafir, capsuni si o dulceata delicata.",
    foodPairings: [
      { dish: "Desert cu capsuni", score: 86 },
      { dish: "Salata de fructe", score: 82 },
      { dish: "Branza proaspata", score: 76 },
    ],
    ratingAvg: 4.0,
    ratingCount: 231,
  },
  {
    slug: "petro-vaselo-bendis-brut",
    name: "Bendis Brut",
    winerySlug: "petro-vaselo",
    regionSlug: "banat",
    type: "sparkling",
    sweetness: "sec",
    vintage: 2020,
    grapeVarieties: [
      { name: "Pinot Noir", slug: "pinot-noir", percentage: 100 },
    ],
    alcohol: 12.5,
    sugar: 8,
    acidity: 6.8,
    priceAvg: 79,
    valueScore: 83,
    giftScore: 88,
    foodMatchScore: 82,
    beginnerFriendly: true,
    cellarPotential: 4,
    overpricedRisk: "medium",
    tastingNotes:
      "Spumant metoda traditionala, fin si crocant, cu mar verde, citrice si crusta de paine.",
    foodPairings: [
      { dish: "Aperitive cu somon", score: 88 },
      { dish: "Stridii", score: 90 },
      { dish: "Pui pane", score: 80 },
    ],
    ratingAvg: 4.3,
    ratingCount: 119,
  },
  {
    slug: "petro-vaselo-ovas-rosu-2020",
    name: "Ovas Rosu",
    winerySlug: "petro-vaselo",
    regionSlug: "banat",
    type: "red",
    sweetness: "sec",
    vintage: 2020,
    grapeVarieties: [
      { name: "Merlot", slug: "merlot", percentage: 60 },
      { name: "Cabernet Sauvignon", slug: "cabernet-sauvignon", percentage: 40 },
    ],
    alcohol: 14,
    sugar: 3.2,
    acidity: 5.3,
    priceAvg: 64,
    valueScore: 82,
    giftScore: 76,
    foodMatchScore: 85,
    beginnerFriendly: false,
    cellarPotential: 6,
    overpricedRisk: "medium",
    tastingNotes:
      "Echilibrat si elegant, cu fructe rosii coapte, ierburi mediteraneene si taninuri fine.",
    foodPairings: [
      { dish: "Friptura de miel", score: 90 },
      { dish: "Paste cu ragu", score: 86 },
      { dish: "Cascaval copt", score: 80 },
    ],
    ratingAvg: 4.2,
    ratingCount: 98,
  },
  {
    slug: "girboiu-epicentrum-alb-2021",
    name: "Epicentrum Alb",
    winerySlug: "crama-girboiu",
    regionSlug: "vrancea",
    type: "white",
    sweetness: "sec",
    vintage: 2021,
    grapeVarieties: [
      { name: "Feteasca Alba", slug: "feteasca-alba", percentage: 50 },
      { name: "Sauvignon Blanc", slug: "sauvignon-blanc", percentage: 50 },
    ],
    alcohol: 13,
    sugar: 2.8,
    acidity: 6.4,
    priceAvg: 41,
    valueScore: 84,
    giftScore: 68,
    foodMatchScore: 83,
    beginnerFriendly: true,
    cellarPotential: 3,
    overpricedRisk: "low",
    tastingNotes:
      "Proaspat si aromat, cu citrice, flori albe si o nota herbacee vie.",
    foodPairings: [
      { dish: "Peste la gratar", score: 88 },
      { dish: "Salata caesar", score: 84 },
      { dish: "Fructe de mare", score: 86 },
    ],
    ratingAvg: 4.1,
    ratingCount: 112,
  },
  {
    slug: "girboiu-bacanta-feteasca-neagra-2020",
    name: "Bacanta Feteasca Neagra",
    winerySlug: "crama-girboiu",
    regionSlug: "vrancea",
    type: "red",
    sweetness: "sec",
    vintage: 2020,
    grapeVarieties: [
      { name: "Feteasca Neagra", slug: "feteasca-neagra", percentage: 100 },
    ],
    alcohol: 13.5,
    sugar: 3.6,
    acidity: 5.5,
    priceAvg: 43,
    valueScore: 83,
    giftScore: 70,
    foodMatchScore: 87,
    beginnerFriendly: true,
    cellarPotential: 4,
    overpricedRisk: "low",
    tastingNotes:
      "Suculent si condimentat, cu prune, mure si un final usor afumat.",
    foodPairings: [
      { dish: "Sarmale", score: 90 },
      { dish: "Mititei", score: 88 },
      { dish: "Tocana de ciuperci", score: 80 },
    ],
    ratingAvg: 4.0,
    ratingCount: 134,
  },
  {
    slug: "lacerta-cuvee-x-2019",
    name: "Cuvee X Rosu",
    winerySlug: "lacerta",
    regionSlug: "dealu-mare",
    type: "red",
    sweetness: "sec",
    vintage: 2019,
    grapeVarieties: [
      { name: "Cabernet Sauvignon", slug: "cabernet-sauvignon", percentage: 40 },
      { name: "Merlot", slug: "merlot", percentage: 35 },
      { name: "Feteasca Neagra", slug: "feteasca-neagra", percentage: 25 },
    ],
    alcohol: 14.5,
    sugar: 3,
    acidity: 5.3,
    priceAvg: 92,
    valueScore: 85,
    giftScore: 89,
    foodMatchScore: 89,
    beginnerFriendly: false,
    cellarPotential: 10,
    overpricedRisk: "medium",
    tastingNotes:
      "Amplu si complex, cu fructe negre, cafea, tutun si taninuri elegante de barrique.",
    foodPairings: [
      { dish: "Antricot de vita", score: 94 },
      { dish: "Rata confiata", score: 88 },
      { dish: "Branzeturi tari", score: 86 },
    ],
    ratingAvg: 4.5,
    ratingCount: 176,
  },
  {
    slug: "lacerta-feteasca-regala-2022",
    name: "Lacerta Feteasca Regala",
    winerySlug: "lacerta",
    regionSlug: "dealu-mare",
    type: "white",
    sweetness: "sec",
    vintage: 2022,
    grapeVarieties: [
      { name: "Feteasca Regala", slug: "feteasca-regala", percentage: 100 },
    ],
    alcohol: 13,
    sugar: 2.6,
    acidity: 6.3,
    priceAvg: 44,
    valueScore: 84,
    giftScore: 68,
    foodMatchScore: 82,
    beginnerFriendly: true,
    cellarPotential: 3,
    overpricedRisk: "low",
    tastingNotes:
      "Crocant si floral, cu mar verde, citrice si o mineralitate racoroasa.",
    foodPairings: [
      { dish: "Peste alb", score: 86 },
      { dish: "Salata cu branza de capra", score: 84 },
      { dish: "Pui la gratar", score: 82 },
    ],
    ratingAvg: 4.1,
    ratingCount: 103,
  },
  {
    slug: "basilescu-eclipse-feteasca-neagra-2021",
    name: "Eclipse Feteasca Neagra",
    winerySlug: "crama-basilescu",
    regionSlug: "dealu-mare",
    type: "red",
    sweetness: "sec",
    vintage: 2021,
    grapeVarieties: [
      { name: "Feteasca Neagra", slug: "feteasca-neagra", percentage: 100 },
    ],
    alcohol: 14,
    sugar: 3.5,
    acidity: 5.4,
    priceAvg: 55,
    valueScore: 86,
    giftScore: 78,
    foodMatchScore: 88,
    beginnerFriendly: false,
    cellarPotential: 6,
    overpricedRisk: "low",
    tastingNotes:
      "Elegant si fructat, cu visine negre, prune si o nota de cacao si piper.",
    foodPairings: [
      { dish: "Sarmale cu mamaliga", score: 92 },
      { dish: "Friptura de porc", score: 88 },
      { dish: "Telemea maturata", score: 80 },
    ],
    ratingAvg: 4.3,
    ratingCount: 158,
  },
  {
    slug: "basilescu-nojlocki-sauvignon-blanc-2022",
    name: "Nojlocki Sauvignon Blanc",
    winerySlug: "crama-basilescu",
    regionSlug: "dealu-mare",
    type: "white",
    sweetness: "sec",
    vintage: 2022,
    grapeVarieties: [
      { name: "Sauvignon Blanc", slug: "sauvignon-blanc", percentage: 100 },
    ],
    alcohol: 13,
    sugar: 2.4,
    acidity: 6.6,
    priceAvg: 48,
    valueScore: 83,
    giftScore: 70,
    foodMatchScore: 82,
    beginnerFriendly: true,
    cellarPotential: 2,
    overpricedRisk: "low",
    tastingNotes:
      "Vibrant si aromat, cu fructul pasiunii, citrice verzi si o tenta herbacee.",
    foodPairings: [
      { dish: "Sushi", score: 86 },
      { dish: "Salata de legume", score: 84 },
      { dish: "Branza de capra", score: 88 },
    ],
    ratingAvg: 4.1,
    ratingCount: 97,
  },
  {
    slug: "jidvei-owners-choice-feteasca-regala-2022",
    name: "Owner's Choice Feteasca Regala",
    winerySlug: "jidvei",
    regionSlug: "tarnave",
    type: "white",
    sweetness: "sec",
    vintage: 2022,
    grapeVarieties: [
      { name: "Feteasca Regala", slug: "feteasca-regala", percentage: 100 },
    ],
    alcohol: 13,
    sugar: 3,
    acidity: 6.5,
    priceAvg: 39,
    valueScore: 87,
    giftScore: 72,
    foodMatchScore: 83,
    beginnerFriendly: true,
    cellarPotential: 3,
    overpricedRisk: "low",
    tastingNotes:
      "Proaspat si elegant, cu flori de camp, mar verde si o aciditate transilvaneana vie.",
    foodPairings: [
      { dish: "Peste la cuptor", score: 86 },
      { dish: "Pui cu legume", score: 84 },
      { dish: "Paste cu legume", score: 82 },
    ],
    ratingAvg: 4.2,
    ratingCount: 287,
  },
  {
    slug: "jidvei-grigorescu-riesling-2021",
    name: "Dr. Grigorescu Riesling de Rhin",
    winerySlug: "jidvei",
    regionSlug: "tarnave",
    type: "white",
    sweetness: "sec",
    vintage: 2021,
    grapeVarieties: [
      { name: "Riesling", slug: "riesling", percentage: 100 },
    ],
    alcohol: 13,
    sugar: 4,
    acidity: 7,
    priceAvg: 58,
    valueScore: 85,
    giftScore: 78,
    foodMatchScore: 85,
    beginnerFriendly: false,
    cellarPotential: 6,
    overpricedRisk: "low",
    tastingNotes:
      "Tensionat si mineral, cu lamaie, piersica alba si o aciditate crocanta de altitudine.",
    foodPairings: [
      { dish: "Fructe de mare", score: 90 },
      { dish: "Peste afumat", score: 86 },
      { dish: "Salata thai", score: 84 },
    ],
    ratingAvg: 4.3,
    ratingCount: 142,
  },
  {
    slug: "jidvei-ana-traditional-brut",
    name: "Ana Spumant Brut",
    winerySlug: "jidvei",
    regionSlug: "tarnave",
    type: "sparkling",
    sweetness: "sec",
    vintage: 2021,
    grapeVarieties: [
      { name: "Chardonnay", slug: "chardonnay", percentage: 60 },
      { name: "Feteasca Regala", slug: "feteasca-regala", percentage: 40 },
    ],
    alcohol: 12,
    sugar: 9,
    acidity: 6.8,
    priceAvg: 52,
    valueScore: 84,
    giftScore: 84,
    foodMatchScore: 80,
    beginnerFriendly: true,
    cellarPotential: 3,
    overpricedRisk: "low",
    tastingNotes:
      "Spumant fin si proaspat, cu mar, citrice si bule persistente.",
    foodPairings: [
      { dish: "Aperitive reci", score: 84 },
      { dish: "Pui pane", score: 82 },
      { dish: "Tort aniversar", score: 80 },
    ],
    ratingAvg: 4.1,
    ratingCount: 201,
  },
  {
    slug: "samburesti-cabernet-sauvignon-2019",
    name: "Samburesti Cabernet Sauvignon",
    winerySlug: "domeniile-samburesti",
    regionSlug: "samburesti",
    type: "red",
    sweetness: "sec",
    vintage: 2019,
    grapeVarieties: [
      { name: "Cabernet Sauvignon", slug: "cabernet-sauvignon", percentage: 100 },
    ],
    alcohol: 14.5,
    sugar: 3,
    acidity: 5.5,
    priceAvg: 51,
    valueScore: 85,
    giftScore: 72,
    foodMatchScore: 88,
    beginnerFriendly: false,
    cellarPotential: 8,
    overpricedRisk: "low",
    tastingNotes:
      "Robust si structurat, cu coacaze negre, piele, tutun si taninuri puternice.",
    foodPairings: [
      { dish: "Friptura de vita", score: 92 },
      { dish: "Tochitura olteneasca", score: 88 },
      { dish: "Branzeturi tari", score: 84 },
    ],
    ratingAvg: 4.2,
    ratingCount: 169,
  },
  {
    slug: "balla-geza-cadarca-2021",
    name: "Stone Wine Cadarca",
    winerySlug: "balla-geza",
    regionSlug: "minis",
    type: "red",
    sweetness: "sec",
    vintage: 2021,
    grapeVarieties: [
      { name: "Cadarca", slug: "cadarca", percentage: 100 },
    ],
    alcohol: 13,
    sugar: 3.4,
    acidity: 5.6,
    priceAvg: 49,
    valueScore: 84,
    giftScore: 72,
    foodMatchScore: 85,
    beginnerFriendly: true,
    cellarPotential: 4,
    overpricedRisk: "low",
    tastingNotes:
      "Usor si fructat, cu fructe rosii proaspete, piper alb si taninuri delicate.",
    foodPairings: [
      { dish: "Carnati de Plescoi", score: 88 },
      { dish: "Gratar de pui", score: 84 },
      { dish: "Ciorba de fasole", score: 78 },
    ],
    ratingAvg: 4.0,
    ratingCount: 88,
  },
  {
    slug: "balla-geza-feteasca-regala-2022",
    name: "Stone Wine Feteasca Regala",
    winerySlug: "balla-geza",
    regionSlug: "minis",
    type: "white",
    sweetness: "sec",
    vintage: 2022,
    grapeVarieties: [
      { name: "Feteasca Regala", slug: "feteasca-regala", percentage: 100 },
    ],
    alcohol: 12.5,
    sugar: 3,
    acidity: 6.4,
    priceAvg: 42,
    valueScore: 83,
    giftScore: 66,
    foodMatchScore: 81,
    beginnerFriendly: true,
    cellarPotential: 3,
    overpricedRisk: "low",
    tastingNotes:
      "Proaspat si floral, cu mar, flori albe si un final mineral.",
    foodPairings: [
      { dish: "Peste alb", score: 84 },
      { dish: "Salata verde", score: 80 },
      { dish: "Pui la cuptor", score: 82 },
    ],
    ratingAvg: 3.9,
    ratingCount: 76,
  },
  {
    slug: "corcova-pinot-noir-2020",
    name: "Corcova Pinot Noir",
    winerySlug: "corcova",
    regionSlug: "oltenia",
    type: "red",
    sweetness: "sec",
    vintage: 2020,
    grapeVarieties: [
      { name: "Pinot Noir", slug: "pinot-noir", percentage: 100 },
    ],
    alcohol: 13.5,
    sugar: 2.8,
    acidity: 5.8,
    priceAvg: 75,
    valueScore: 84,
    giftScore: 82,
    foodMatchScore: 86,
    beginnerFriendly: false,
    cellarPotential: 6,
    overpricedRisk: "medium",
    tastingNotes:
      "Fin si elegant, cu zmeura, cireșe, note de pamant si taninuri matasoase.",
    foodPairings: [
      { dish: "Rata la cuptor", score: 90 },
      { dish: "Ciuperci sote", score: 86 },
      { dish: "Somon la gratar", score: 84 },
    ],
    ratingAvg: 4.3,
    ratingCount: 124,
  },
  {
    slug: "corcova-riesling-italian-2022",
    name: "Corcova Riesling Italian",
    winerySlug: "corcova",
    regionSlug: "oltenia",
    type: "white",
    sweetness: "sec",
    vintage: 2022,
    grapeVarieties: [
      { name: "Riesling", slug: "riesling", percentage: 100 },
    ],
    alcohol: 12.5,
    sugar: 3.2,
    acidity: 6.8,
    priceAvg: 45,
    valueScore: 83,
    giftScore: 68,
    foodMatchScore: 83,
    beginnerFriendly: true,
    cellarPotential: 3,
    overpricedRisk: "low",
    tastingNotes:
      "Proaspat si citric, cu lamaie verde, mar si o aciditate vie.",
    foodPairings: [
      { dish: "Fructe de mare", score: 86 },
      { dish: "Peste prajit", score: 84 },
      { dish: "Salata de paste", score: 80 },
    ],
    ratingAvg: 4.0,
    ratingCount: 91,
  },
  {
    slug: "stirbey-cramposie-selectionata-2022",
    name: "Prince Stirbey Cramposie Selectionata",
    winerySlug: "prince-stirbey",
    regionSlug: "dragasani",
    type: "white",
    sweetness: "sec",
    vintage: 2022,
    grapeVarieties: [
      { name: "Cramposie Selectionata", slug: "cramposie-selectionata", percentage: 100 },
    ],
    alcohol: 12,
    sugar: 2.2,
    acidity: 7,
    priceAvg: 54,
    valueScore: 86,
    giftScore: 74,
    foodMatchScore: 84,
    beginnerFriendly: true,
    cellarPotential: 3,
    overpricedRisk: "low",
    tastingNotes:
      "Crocant si vioi, cu citrice, mar verde si o aciditate salivanta, soi autohton rar.",
    foodPairings: [
      { dish: "Fructe de mare", score: 88 },
      { dish: "Peste la gratar", score: 86 },
      { dish: "Salata de cruditati", score: 82 },
    ],
    ratingAvg: 4.3,
    ratingCount: 108,
  },
  {
    slug: "stirbey-negru-de-dragasani-2020",
    name: "Prince Stirbey Negru de Dragasani",
    winerySlug: "prince-stirbey",
    regionSlug: "dragasani",
    type: "red",
    sweetness: "sec",
    vintage: 2020,
    grapeVarieties: [
      { name: "Negru de Dragasani", slug: "negru-de-dragasani", percentage: 100 },
    ],
    alcohol: 14,
    sugar: 3,
    acidity: 5.5,
    priceAvg: 89,
    valueScore: 85,
    giftScore: 84,
    foodMatchScore: 88,
    beginnerFriendly: false,
    cellarPotential: 9,
    overpricedRisk: "medium",
    tastingNotes:
      "Condimentat si profund, cu fructe negre, piper, ierburi uscate si taninuri ferme.",
    foodPairings: [
      { dish: "Vanat", score: 92 },
      { dish: "Friptura de berbecut", score: 90 },
      { dish: "Branzeturi maturate", score: 84 },
    ],
    ratingAvg: 4.4,
    ratingCount: 137,
  },
  {
    slug: "stirbey-novac-2021",
    name: "Prince Stirbey Novac",
    winerySlug: "prince-stirbey",
    regionSlug: "dragasani",
    type: "red",
    sweetness: "sec",
    vintage: 2021,
    grapeVarieties: [
      { name: "Novac", slug: "novac", percentage: 100 },
    ],
    alcohol: 13.5,
    sugar: 3.2,
    acidity: 5.6,
    priceAvg: 72,
    valueScore: 84,
    giftScore: 80,
    foodMatchScore: 86,
    beginnerFriendly: false,
    cellarPotential: 6,
    overpricedRisk: "medium",
    tastingNotes:
      "Suculent si aromat, cu mure, prune si un profil condimentat distinctiv.",
    foodPairings: [
      { dish: "Mici", score: 88 },
      { dish: "Tochitura", score: 90 },
      { dish: "Cascaval la gratar", score: 80 },
    ],
    ratingAvg: 4.2,
    ratingCount: 102,
  },
  {
    slug: "vinarte-prince-matei-merlot-2018",
    name: "Prince Matei Merlot",
    winerySlug: "vinarte",
    regionSlug: "dealu-mare",
    type: "red",
    sweetness: "sec",
    vintage: 2018,
    grapeVarieties: [
      { name: "Merlot", slug: "merlot", percentage: 100 },
    ],
    alcohol: 14.5,
    sugar: 3,
    acidity: 5.2,
    priceAvg: 165,
    valueScore: 80,
    giftScore: 92,
    foodMatchScore: 88,
    beginnerFriendly: false,
    cellarPotential: 12,
    overpricedRisk: "high",
    tastingNotes:
      "Bogat si opulent, cu prune confiate, ciocolata neagra, vanilie si taninuri catifelate.",
    foodPairings: [
      { dish: "Antricot de vita", score: 92 },
      { dish: "Rata confiata", score: 88 },
      { dish: "Branzeturi nobile", score: 86 },
    ],
    ratingAvg: 4.5,
    ratingCount: 143,
  },
  {
    slug: "vinarte-soare-cabernet-2020",
    name: "Soare Cabernet Sauvignon",
    winerySlug: "vinarte",
    regionSlug: "dealu-mare",
    type: "red",
    sweetness: "sec",
    vintage: 2020,
    grapeVarieties: [
      { name: "Cabernet Sauvignon", slug: "cabernet-sauvignon", percentage: 100 },
    ],
    alcohol: 14,
    sugar: 3.4,
    acidity: 5.4,
    priceAvg: 62,
    valueScore: 82,
    giftScore: 78,
    foodMatchScore: 85,
    beginnerFriendly: false,
    cellarPotential: 7,
    overpricedRisk: "medium",
    tastingNotes:
      "Cald si generos, cu fructe negre coapte, cedru si un final lung, condimentat.",
    foodPairings: [
      { dish: "Friptura la gratar", score: 90 },
      { dish: "Mancare de vanat", score: 88 },
      { dish: "Cascaval afumat", score: 80 },
    ],
    ratingAvg: 4.1,
    ratingCount: 116,
  },
  {
    slug: "halewood-la-umbra-feteasca-neagra-2021",
    name: "La Umbra Feteasca Neagra",
    winerySlug: "halewood",
    regionSlug: "dealu-mare",
    type: "red",
    sweetness: "sec",
    vintage: 2021,
    grapeVarieties: [
      { name: "Feteasca Neagra", slug: "feteasca-neagra", percentage: 100 },
    ],
    alcohol: 13.5,
    sugar: 4,
    acidity: 5.5,
    priceAvg: 29,
    valueScore: 88,
    giftScore: 58,
    foodMatchScore: 86,
    beginnerFriendly: true,
    cellarPotential: 3,
    overpricedRisk: "low",
    tastingNotes:
      "Accesibil si fructat, cu prune, visine si un final usor condimentat.",
    foodPairings: [
      { dish: "Sarmale", score: 88 },
      { dish: "Mici", score: 86 },
      { dish: "Pizza", score: 80 },
    ],
    ratingAvg: 4.0,
    ratingCount: 342,
  },
  {
    slug: "halewood-colina-piatra-alba-2022",
    name: "Colina Piatra Alba",
    winerySlug: "halewood",
    regionSlug: "dealu-mare",
    type: "white",
    sweetness: "sec",
    vintage: 2022,
    grapeVarieties: [
      { name: "Feteasca Alba", slug: "feteasca-alba", percentage: 70 },
      { name: "Sauvignon Blanc", slug: "sauvignon-blanc", percentage: 30 },
    ],
    alcohol: 12.5,
    sugar: 3,
    acidity: 6.2,
    priceAvg: 27,
    valueScore: 86,
    giftScore: 56,
    foodMatchScore: 81,
    beginnerFriendly: true,
    cellarPotential: 2,
    overpricedRisk: "low",
    tastingNotes:
      "Usor si proaspat, cu flori albe, citrice si o nota crocanta de mar.",
    foodPairings: [
      { dish: "Salata", score: 82 },
      { dish: "Peste prajit", score: 84 },
      { dish: "Aperitive reci", score: 80 },
    ],
    ratingAvg: 3.9,
    ratingCount: 268,
  },
  {
    slug: "villa-vinea-selection-pinot-noir-2020",
    name: "Selection Pinot Noir",
    winerySlug: "villa-vinea",
    regionSlug: "tarnave",
    type: "red",
    sweetness: "sec",
    vintage: 2020,
    grapeVarieties: [
      { name: "Pinot Noir", slug: "pinot-noir", percentage: 100 },
    ],
    alcohol: 13,
    sugar: 2.6,
    acidity: 5.9,
    priceAvg: 68,
    valueScore: 84,
    giftScore: 80,
    foodMatchScore: 85,
    beginnerFriendly: false,
    cellarPotential: 6,
    overpricedRisk: "medium",
    tastingNotes:
      "Delicat si rafinat, cu fructe rosii proaspete, note florale si taninuri fine.",
    foodPairings: [
      { dish: "Rata", score: 88 },
      { dish: "Ciuperci", score: 86 },
      { dish: "Somon", score: 84 },
    ],
    ratingAvg: 4.2,
    ratingCount: 94,
  },
  {
    slug: "villa-vinea-pinot-gris-2022",
    name: "Villa Vinea Pinot Gris",
    winerySlug: "villa-vinea",
    regionSlug: "tarnave",
    type: "white",
    sweetness: "sec",
    vintage: 2022,
    grapeVarieties: [
      { name: "Pinot Gris", slug: "pinot-gris", percentage: 100 },
    ],
    alcohol: 13.5,
    sugar: 3.5,
    acidity: 6,
    priceAvg: 56,
    valueScore: 83,
    giftScore: 74,
    foodMatchScore: 84,
    beginnerFriendly: true,
    cellarPotential: 4,
    overpricedRisk: "low",
    tastingNotes:
      "Corp mediu si catifelat, cu fructe albe coapte, miere fina si un final lung.",
    foodPairings: [
      { dish: "Pui cu smantana", score: 86 },
      { dish: "Risotto", score: 84 },
      { dish: "Branza moale", score: 82 },
    ],
    ratingAvg: 4.1,
    ratingCount: 87,
  },
  {
    slug: "davino-rezerva-rosu-2018",
    name: "Davino Rezerva",
    winerySlug: "davino",
    regionSlug: "dealu-mare",
    type: "red",
    sweetness: "sec",
    vintage: 2018,
    grapeVarieties: [
      { name: "Cabernet Sauvignon", slug: "cabernet-sauvignon", percentage: 40 },
      { name: "Merlot", slug: "merlot", percentage: 30 },
      { name: "Feteasca Neagra", slug: "feteasca-neagra", percentage: 30 },
    ],
    alcohol: 14.5,
    sugar: 2.8,
    acidity: 5.3,
    priceAvg: 220,
    valueScore: 83,
    giftScore: 95,
    foodMatchScore: 90,
    beginnerFriendly: false,
    cellarPotential: 15,
    overpricedRisk: "medium",
    tastingNotes:
      "Iconic si complex, cu fructe negre, trufe, tutun, mirodenii si taninuri nobile, indelung maturat.",
    foodPairings: [
      { dish: "Mușchi de vita Wellington", score: 95 },
      { dish: "Vanat in sos de vin", score: 92 },
      { dish: "Branzeturi maturate", score: 88 },
    ],
    ratingAvg: 4.7,
    ratingCount: 221,
  },
  {
    slug: "avincis-negru-de-dragasani-2020",
    name: "Avincis Negru de Dragasani",
    winerySlug: "avincis",
    regionSlug: "dragasani",
    type: "red",
    sweetness: "sec",
    vintage: 2020,
    grapeVarieties: [
      { name: "Negru de Dragasani", slug: "negru-de-dragasani", percentage: 100 },
    ],
    alcohol: 14,
    sugar: 3,
    acidity: 5.5,
    priceAvg: 78,
    valueScore: 85,
    giftScore: 82,
    foodMatchScore: 88,
    beginnerFriendly: false,
    cellarPotential: 8,
    overpricedRisk: "medium",
    tastingNotes:
      "Profund si condimentat, cu mure, piper negru, ierburi si taninuri structurate.",
    foodPairings: [
      { dish: "Friptura de vanat", score: 92 },
      { dish: "Tochitura", score: 88 },
      { dish: "Branza maturata", score: 84 },
    ],
    ratingAvg: 4.4,
    ratingCount: 129,
  },
  {
    slug: "liliac-private-selection-pinot-noir-2021",
    name: "Liliac Private Selection Pinot Noir",
    winerySlug: "liliac",
    regionSlug: "lechinta",
    type: "red",
    sweetness: "sec",
    vintage: 2021,
    grapeVarieties: [
      { name: "Pinot Noir", slug: "pinot-noir", percentage: 100 },
    ],
    alcohol: 13,
    sugar: 2.5,
    acidity: 5.9,
    priceAvg: 88,
    valueScore: 83,
    giftScore: 84,
    foodMatchScore: 85,
    beginnerFriendly: false,
    cellarPotential: 7,
    overpricedRisk: "medium",
    tastingNotes:
      "Elegant si proaspat, cu cireșe, zmeura si o tenta minerala de altitudine.",
    foodPairings: [
      { dish: "Rata cu sos de visine", score: 90 },
      { dish: "Ciuperci la gratar", score: 86 },
      { dish: "Somon", score: 84 },
    ],
    ratingAvg: 4.3,
    ratingCount: 111,
  },
  {
    slug: "budureasca-origini-rosu-2019",
    name: "Origini Rosu",
    winerySlug: "budureasca",
    regionSlug: "dealu-mare",
    type: "red",
    sweetness: "sec",
    vintage: 2019,
    grapeVarieties: [
      { name: "Feteasca Neagra", slug: "feteasca-neagra", percentage: 50 },
      { name: "Cabernet Sauvignon", slug: "cabernet-sauvignon", percentage: 30 },
      { name: "Merlot", slug: "merlot", percentage: 20 },
    ],
    alcohol: 14,
    sugar: 3.2,
    acidity: 5.3,
    priceAvg: 74,
    valueScore: 85,
    giftScore: 84,
    foodMatchScore: 89,
    beginnerFriendly: false,
    cellarPotential: 9,
    overpricedRisk: "low",
    tastingNotes:
      "Complex si echilibrat, cu fructe negre, condimente, cafea si taninuri rotunde.",
    foodPairings: [
      { dish: "Friptura de vita", score: 92 },
      { dish: "Sarmale", score: 88 },
      { dish: "Branzeturi tari", score: 84 },
    ],
    ratingAvg: 4.4,
    ratingCount: 187,
  },
  {
    slug: "cramele-recas-cervus-cabernet-2021",
    name: "Cervus Cabernet Sauvignon",
    winerySlug: "cramele-recas",
    regionSlug: "recas",
    type: "red",
    sweetness: "sec",
    vintage: 2021,
    grapeVarieties: [
      { name: "Cabernet Sauvignon", slug: "cabernet-sauvignon", percentage: 100 },
    ],
    alcohol: 13.5,
    sugar: 4.5,
    acidity: 5.2,
    priceAvg: 26,
    valueScore: 89,
    giftScore: 56,
    foodMatchScore: 84,
    beginnerFriendly: true,
    cellarPotential: 3,
    overpricedRisk: "low",
    tastingNotes:
      "Fructat si accesibil, cu fructe negre, o nota de vanilie si taninuri moi.",
    foodPairings: [
      { dish: "Gratar", score: 88 },
      { dish: "Burger", score: 86 },
      { dish: "Pizza", score: 82 },
    ],
    ratingAvg: 4.0,
    ratingCount: 456,
  },
  {
    slug: "casa-de-vinuri-cotnari-busuioaca-2022",
    name: "Busuioaca de Bohotin",
    winerySlug: "casa-de-vinuri-cotnari",
    regionSlug: "cotnari",
    type: "rose",
    sweetness: "demidulce",
    vintage: 2022,
    grapeVarieties: [
      { name: "Busuioaca de Bohotin", slug: "busuioaca-de-bohotin", percentage: 100 },
    ],
    alcohol: 12,
    sugar: 20,
    acidity: 6.3,
    priceAvg: 33,
    valueScore: 82,
    giftScore: 68,
    foodMatchScore: 77,
    beginnerFriendly: true,
    cellarPotential: 2,
    overpricedRisk: "low",
    tastingNotes:
      "Parfumat si delicat, cu petale de trandafir, capsuni si o dulceata fina, echilibrata.",
    foodPairings: [
      { dish: "Desert cu fructe rosii", score: 86 },
      { dish: "Salata de fructe", score: 82 },
      { dish: "Branza dulce", score: 76 },
    ],
    ratingAvg: 4.1,
    ratingCount: 178,
  },
];

function availabilityFor(price: number): AvailabilityEntry[] {
  return [
    {
      retailer: "Vinul.ro",
      url: "https://vinul.ro",
      priceRon: price,
      inStock: true,
    },
    {
      retailer: "Carrefour",
      priceRon: Math.round(price * 1.05),
      inStock: true,
    },
  ];
}

function affiliatesFor(price: number): AffiliateLink[] {
  return [
    { retailer: "Vinul.ro", url: "https://vinul.ro", priceRon: price },
  ];
}

async function main() {
  console.log("Curatare tabele existente...");
  await db.delete(wines);
  await db.delete(wineries);
  await db.delete(grapeVarieties);
  await db.delete(regions);

  console.log("Inserare regiuni...");
  const regionRows = await db.insert(regions).values(regionSeed).returning();
  const regionId = (slug: string) => {
    const row = regionRows.find((r) => r.slug === slug);
    if (!row) throw new Error(`Region not found: ${slug}`);
    return row.id;
  };

  console.log("Inserare soiuri...");
  await db.insert(grapeVarieties).values(grapeSeed);

  console.log("Inserare crame...");
  const wineryRows = await db
    .insert(wineries)
    .values(
      winerySeed.map((w) => ({
        slug: w.slug,
        name: w.name,
        regionId: regionId(w.regionSlug),
        verified: w.verified,
        foundedYear: w.foundedYear,
        website: w.website,
        description: w.description,
      })),
    )
    .returning();
  const wineryId = (slug: string) => {
    const row = wineryRows.find((w) => w.slug === slug);
    if (!row) throw new Error(`Winery not found: ${slug}`);
    return row.id;
  };

  console.log("Inserare vinuri...");
  const wineryNameBySlug = new Map(winerySeed.map((w) => [w.slug, w.name]));

  await db.insert(wines).values(
    wineSeed.map((w) => ({
      slug: w.slug,
      name: w.name,
      wineryId: wineryId(w.winerySlug),
      regionId: regionId(w.regionSlug),
      type: w.type,
      sweetness: w.sweetness,
      vintage: w.vintage,
      grapeVarieties: w.grapeVarieties,
      alcohol: w.alcohol,
      sugar: w.sugar,
      acidity: w.acidity,
      priceAvg: w.priceAvg,
      valueScore: w.valueScore,
      giftScore: w.giftScore,
      foodMatchScore: w.foodMatchScore,
      beginnerFriendly: w.beginnerFriendly,
      cellarPotential: w.cellarPotential,
      overpricedRisk: w.overpricedRisk,
      tastingNotes: w.tastingNotes,
      foodPairings: w.foodPairings,
      availability: availabilityFor(w.priceAvg),
      affiliateLinks: affiliatesFor(w.priceAvg),
      imageUrl: w.imageUrl ?? null,
      imageAlt:
        w.imageAlt ??
        buildWineImageAlt({
          name: w.name,
          vintage: w.vintage,
          type: w.type,
          wineryName: wineryNameBySlug.get(w.winerySlug),
        }),
      ratingAvg: w.ratingAvg,
      ratingCount: w.ratingCount,
      status: "verified" as const,
    })),
  );

  console.log(
    `Gata. ${regionRows.length} regiuni, ${grapeSeed.length} soiuri, ${wineryRows.length} crame, ${wineSeed.length} vinuri.`,
  );
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
